### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by Robinlovelace** [udsleeds/openinfra#103]
I think this is a solid basis of a logo: 
![image](https://user-images.githubusercontent.com/1825120/185739316-4ba87157-aab3-4d92-bf4c-5960e509e0c8.png)

Can we have a bash at putting this in a nice hex sticker? Pre-requisite for fun-loving R package builders! 

https://github.com/GuangchuangYu/hexSticker

**Comment by hulsiejames** [comment]
![openinfra_hex_logo](https://user-images.githubusercontent.com/58815827/185742411-45af7076-65ae-4eea-99a9-1fbc21bda6da.png)
It's a start, but by no means finished - but shows it will work. 

Would like to have a [transparent background](https://stackoverflow.com/questions/7455046/how-to-make-graphics-with-transparent-background-in-r-using-ggplot2) to get rid of the white background and plot boarder.

**Comment by Robinlovelace** [comment]
Looking good! I vote make the map take up the entire hex and also render the network as part of the creation process.

**Comment by GretaTimaite** [comment]
some reproducible code for ggplot

```{r}
library(ggplot2)
library(hexSticker)

plot = ggplot2::ggplot(data = sotm_data)+
  ggplot2::geom_sf(ggplot2::aes())

plot1 = plot + ggplot2::theme_void() + hexSticker::theme_transparent()

sticker(plot1, package="hexSticker", p_size=20, s_x=1, s_y=.75, s_width=1.3, s_height=1,
        filename="ggplot2.png")
```

**Comment by Robinlovelace** [comment]
Heads-up @hulsiejames and @GretaTimaite looking at this now after request from the Leeds Digital Festival people.

**Comment by Robinlovelace** [comment]
Plan, edit the image above in the browser-based app http://viliusle.github.io/miniPaint/

**Comment by Robinlovelace** [comment]
Work in progress...

![image](https://user-images.githubusercontent.com/1825120/191452643-46870b09-3a78-45d2-a175-793e1bbbe0d4.png)

**Comment by Robinlovelace** [comment]
![openinfra](https://user-images.githubusercontent.com/1825120/191453030-789924c5-a3c4-4ff4-8bb6-0e782e5a85d3.png)

Good enough for now? Can reopen if we need to update the logo...

**Comment by Robinlovelace** [comment]
Just cc'd you into an email for context.

**Comment by hulsiejames** [comment]
Very nice! I had another go with HexSticker last weekend, but much prefer the quality of the result you have achieved. Browser based paint looks cool too. 

![](https://i.imgur.com/BqhurYD.png)

![](https://i.imgur.com/VkNFDCB.png)
