### ISSUE TITLE
oi_clean_maxspeed_uk

### ISSUE THREAD

**Issue by hulsiejames** [udsleeds/openinfra#104]
TODO: 

Double checkt that inference of `maxspeed="national"` == "70 mph" when on a dual carriage way is correct. 

This is only true when there is a physical seperation inbetween the carriage ways, thus, a hedge or intermittent barriers would mean `maxspeed="national"` == "60 mph"

Check OSM tags to see if dual carriage ways have the type of seperation listed - if so then add logic that can determin between 60mph and 70mph

**Comment by GretaTimaite** [comment]
Just thinking that it could be useful to write an R function based on Tobias Zwick's work + it could be a good opportunity to provide feedback to him?
[Wiki](https://wiki.openstreetmap.org/wiki/Default_speed_limits#cite_note-:1-186)
[Tool](https://westnordost.github.io/osm-legal-default-speeds/)

**Comment by hulsiejames** [comment]
[3883c83](https://github.com/udsleeds/openinfra/commit/3883c833cbd6db0ffb0ef2601fad8955e1b9c57c) Has changed the case when analysing a dual carriage way to set "national" to 70 mph. 

Simply put, there does not seem to be enough data to determine if there is a physical barrier on a dual carraige way.

However, it seems that when physical separation is present, mappers have already applied maxspeed = "70 mph" rather than "national", or any other speed limit. 

As such, I have changed the default assumption to state "national" as "60 mph" - in the (small chance) situation that there is a dual carriage way with physical separation and maxspeed = "national", I would rather recategorise this down to "60mph", than incorrectly raise the limit of a dual carrirage way with no separation to "70 mph".

^This resoning is also stated within the function code.
