### ISSUE TITLE
walking accessibility proportions in different areas

### ISSUE THREAD

**Issue by GretaTimaite** [udsleeds/openinfra#11]
<img width="1416" alt="Screenshot 2021-11-20 at 11 21 34" src="https://user-images.githubusercontent.com/84614994/142724850-49f8a0ef-f4af-497d-934c-bac4bc095a94.png">

Started looking at Greater Manchester and made this plot to compare some keys/tags between the two zones. I'm quite surprised that GM is not much more extensively mapped than WY . Indeed, foot is quite significantly more mapped in WY.

Just to note that footway in this graph refers to key:footway and not highway=footway.

**Comment by GretaTimaite** [comment]
After an initial pedestrian network recategorization (see #8), I've calculated proportions and compared them between WY and GM.

<img width="734" alt="Screenshot 2021-11-24 at 14 32 48" src="https://user-images.githubusercontent.com/84614994/143239056-6ecdc1cc-015f-4fdb-9739-174a7b2438aa.png">

Very interesting that they have the same "yes" proportion and are very similar in terms of the proportion of network that is *not* accessible to pedestrians (note, percents are rounded to 2 significant numbers). 

The questions that bugs me is how much WY and GM differs regarding the presence of information on accessibility...

**Comment by Robinlovelace** [comment]
Very interesting, especially the differences in data provision between WY and MCR.

**Comment by GretaTimaite** [comment]
Finally downloaded Greater London OSM data and pretty surprised with the results. I wouldn't say it has more data for these tags than WY, GM, or Merseyside. 
![Screenshot 2022-01-19 at 07 48 37](https://user-images.githubusercontent.com/84614994/150086778-4573d4ff-067d-455d-8b3d-4629ed557eea.png)
![Screenshot 2022-01-19 at 07 48 54](https://user-images.githubusercontent.com/84614994/150086813-efdd08e1-56e6-4957-b23e-c061b79001f5.png)
![Screenshot 2022-01-19 at 07 49 10](https://user-images.githubusercontent.com/84614994/150086862-7d9130fe-c8e6-4d21-a416-003a98b82126.png)

Of course, for more robust analysis data should be cleaned better because, for example, there's width == "60 cm" but my code assumes that everything is measured in meters.

Also had a look at where all the kerb data disappears and it seems to be tagged mostly to is.na(highway)
```
gl %>% filter(is.na(highway) & !is.na(kerb)) %>% nrow()
#> 4020 rows
gl %>% filter(!is.na(kerb)) %>% nrow()
#> 4053
# almost all of the kerbs are tagged to is.na(highway).
# a large proportion of kerb data is waterway and aerialway atttribute
gl %>% filter(highway == "waterway" | highway == "aerialway" & kerb == "lowered" | kerb == "flush") %>% nrow()
```

**Comment by GretaTimaite** [comment]
very interesting. Your hypothesis that Greater London should have a comprehensive cycling and pedestrian network is correct but besides that it doesn't stand out _that_ much. It does have more data on sidewalks, for instance, but not as much as I expected. Width tag disappointed me. 
![Screenshot 2022-01-19 at 09 33 25](https://user-images.githubusercontent.com/84614994/150103398-3355943c-ae80-4e61-8b0f-eee895309722.png)
![Screenshot 2022-01-19 at 09 33 42](https://user-images.githubusercontent.com/84614994/150103409-05302391-cc3d-47df-b8c0-c4e23d6a9d07.png)
![Screenshot 2022-01-19 at 09 33 49](https://user-images.githubusercontent.com/84614994/150103416-290b617c-9c70-4fbf-8799-ab655e486b83.png)

I checked if, by any chance, `est_width` tag is used extensively instead of `width`. It's not really a case, especially in GM (surprised) and Merseyside
```
gl %>% filter(!is.na(est_width)) %>% nrow()
#> 680
mers %>% filter(!is.na(est_width)) %>% nrow
#> 10
gm %>% filter(!is.na(est_width)) %>% nrow()
#> 17
wy %>% filter(!is.na(est_width)) %>% nrow()
#> 261
```
