### ISSUE TITLE
Basecamp message

### ISSUE THREAD

**Issue by Robinlovelace** [udsleeds/openinfra#120]
Hi @hulsiejames and anyone else watching, I've just drafted the following message in response to a query on the DfT's forum for active travel posted by a local authority planner looking to better map their cycle network. Seem reasonable?

Hi everyone,

A basic starting point for this may be our Data Packs, see here for the raw data generated by my colleague James Hulse: https://github.com/udsleeds/openinfra/releases/tag/0.4

Download the .geojson (or slightly more compressed and performant .gpkg) file for your area and you can import it into the GIS of your choice. Recommendation: QGIS which has lots of support for CAD and editing.

In fact we're looking for feedback on the data packs. For a bit more context/info please see one or more of the links below, depending on your interest, ranging from the 'get me started' to 'deep dive' interests:

1) Intro to the project in broad terms (see lots of info in here including a tutorial on QGIS https://udsleeds.github.io/openinfra/articles/QGIS_OSM_Setup.html in the Articles button on this page): https://udsleeds.github.io/openinfra/

2) Video where James presented the latest version of these data packs as they were around a month ago (they have evolved a bit and been made available nationwide since then): https://youtu.be/4QH5bJqikPE

3) Paper just presented at the State of the Map conference on OpenStreetMap where we got lots of good feedback on this: https://doi.org/10.5281/zenodo.7004509

4) Our issue tracker where we encourage people to ask questions and get involved (not only are the data packs, which are still a work in progress, open, so is the underlying code, for future-proof-ness and transparency). Note: to comment you need a GitHub account. Any replies here also very welcome.

One idea is for Active Travel England, DfT, or another national organisation to take this in house to support transport planners nationwide. Another is to provide tools to help with the job of mapping active travel infrastructure in some kind of Active Travel Infrastructure Platform, any thoughts on such a tool also very welcome. No promises but I am in conversations that could help towards such a platform becoming available.

**Comment by hulsiejames** [comment]
Hi Robin, Hope you enjoyed the rest of your time in Italy!  

This sounds like a great response and a good opportunity to obtain some more feedback on the data packs.  

A quick addition, as the local planner seems to have a specific interest on cycling infrastructure, and based on some feedback from Kayley, would be mentioning the (soon to be added) bicycle parking points and LTN1/20 guidance compliance within the data packs which will contain much more useful information (if the cycling infrastructure is a cycle lane, or if there is some segregation, or simply a road with low traffic speeds thus suitable for cyclists) with regards to cycling infrastructure than the current `oi_cycle` output. 

In fact, I had tried to upload a new version of the data packs (now also contains a points layer data pack, currently only has `amenity="bicycle_parking"`) to 0.4.1 releases over the weekend, though it seems these haven't been uploaded (currently investigating)

**Comment by hulsiejames** [comment]
Sounds good. Thank you for the invite to basecamp.
