### ISSUE TITLE
Should we rename the columns with a different or no prefix

### ISSUE THREAD

**Issue by Robinlovelace** [udsleeds/openinfra#122]
Currently all columns generated by our code have the prefix `io_`. This is potentially confusing. 2 options jump to mind:

- Remove the prefix completely
- Use a more understandable prefix, e.g. `openinfra_`

Pros and cons, interested to hear what people think or other ideas...

**Comment by hulsiejames** [comment]
Personally, I prefer the use of `openinfra_`, provided this does not end up creating column names which are too long. 

That being said, I don't think there are column name character limits (unlike shapefiles) and so, in my opinion, whilst viewing data packs in a tabular format may be messy with longer column names, the benefit of more intuitive and descriptive column names outweighs this.

**Comment by Robinlovelace** [comment]
I like the explicit `openinfra_` prefix too so happy to go with that :+1: 

Nice to have a simple solution sometimes!

**Comment by GretaTimaite** [comment]
I vote for `openinfra_` as well. 
Also it is advised to have a common prefix for all the functions in a given package as then autocomplete can be utilised:
"Use a common prefix to indicate that they are connected. That’s better than a common suffix because autocomplete allows you to type the prefix and see all the members of the family." from [R for Data Science](https://r4ds.had.co.nz/functions.html).

**Comment by hulsiejames** [comment]
>Also it is advised to have a common prefix for all the functions in a given package as then autocomplete can be utilised:

This is a good point. 

Currently all of the **o**pen**i**nfra functions do use the same prefix `oi_` - I thought this was similar to the `oe_` used by **o**sm**e**xtract, and the auto complete feature works well. 

![Screenshot from 2022-09-01 15-06-16](https://user-images.githubusercontent.com/58815827/187934241-842ae533-9d96-4e2c-972e-54ca31ed0537.png)

Should we consider changing this prefix to `openinfra_` too?

Personally I think `oi_` for function prefix works well as this is less to type into a script before bringing up auto complete promts. Additionally, the auto complete prompt does already mention the {openinfra} package name next to each function.

**Comment by Robinlovelace** [comment]
`openinfra_` for data and `oi_` for functions is ideal IMO.
