### ISSUE TITLE
Walking and cycling innovations abstract submission

### ISSUE THREAD

**Issue by Robinlovelace** [udsleeds/openinfra#124]
In Manchester. Deadline for this one: 7th September: 

> 
> If you'd like to be considered for inclusion on the programme, please send ideas to [Juliana O'Rourke](mailto:juliana.orourke@landor.co.uk?subject=Walking%20%2B%20Cycling%20Innovations%202022%20-%20paper) by 17.00 on Wednesday 7th September 2022, to include:
> 
>     Talk title
>     Short description (max 250 words)
>     Speaker name, job title and contact details

https://www.transportxtra.com/tx-events/2632/cycling-walking-innovations-2022

**Comment by hulsiejames** [comment]
Like the look of this! - some information from the link, **bold** seem more relevant.

> **The programme will include presentations, case studies and demonstrations in the following areas**:
>
>- **Data collection, counting, analysis and toolkits**
>- Street engineering innovation
>- Improving safety for all road users
>- **Walking and cycling network design**
>- Mapping and wayfinding
>- **Accessibility planning**
>- LTNs
>- School streets
>- Apps and journey planners
>- Parklets and green infrastructure
>- Mobility hubs
>- Behaviour change tools
>- **Cycling amenities**
>- Consultancy and design
>- **Bollards, lighting and active travel infrastructure**
>- Appraisal, monitoring and evaluation tools


_____________________________________________________________________________________________________

> **Topics include**:
>- The walking and cycling revolution outlined in the July 2020 Gear Change plan, aimed at making England ‘a great walking and cycling nation’, sets out the actions needed to make this a reality
>- **better streets for cycling and people**
>- **cycling and walking at the heart of decision-making**
>- **empowering and encouraging local authorities**
>- **enabling people to walk and cycle, and protecting them when they do**

**Comment by GretaTimaite** [comment]
Good luck if you're applying. My schedule is already a bit too busy for this.
