### ISSUE TITLE
Splitting up oi_inclusive_mobility() function

### ISSUE THREAD

**Issue by GretaTimaite** [udsleeds/openinfra#129]
This is a follow up to my comment on #116.

I've noticed that some of the stuff James and I have done (e.g., presence of lighting) have started to overlap. For example, oi_inclusive_mobility returns lit column as it's important for inclusive spaces, but James created a separate function for it as well. This, I believe creates some redundancy and unnecessary confusion as the current amount of OSM data on lighting does not permit saying more than that the lighting is present, not, or maybe.

Thus, I'm wondering if it would make sense to split up oi_inclusive_mobility(), so instead of having a function that returns 6 columns in bunch, we would have a function for each column. If not, then I guess we need to make it clear in the documentation why oi_inclusive_mobility() returns lit column as well as why we have, e.g., oi_lit() function and that both basically do the same (James include "maybe" option but I do not as basically I treat everything as "non-existing" unless it can be deduced with certainty that a feature exists).

Any thoughts @hulsiejames, @Robinlovelace?

**Comment by GretaTimaite** [comment]
To do if a function ceases to exist in its current form: 

- [ ] update sotm2022 code

**Comment by Robinlovelace** [comment]
I think splitting things into modular components is a good thing, :+1: to this!

**Comment by hulsiejames** [comment]
Yes, I am a big advocate for splitting this into multiple sub-functions!
