### ISSUE TITLE
Print out map for feedback + event

### ISSUE THREAD

**Issue by Robinlovelace** [udsleeds/openinfra#13]
Sketch of idea: 

![image](https://user-images.githubusercontent.com/1825120/143592192-f2c49826-968c-4b42-9d15-ad3fd4374d32.png)

**Comment by Robinlovelace** [comment]
Heads-up @GretaTimaite I'm taking a look at this...

**Comment by Robinlovelace** [comment]
Looking at this as a bounding box so it's zoomed-in.

![image](https://user-images.githubusercontent.com/1825120/143825392-7653b987-c586-4de1-8354-11746123c25d.png)

**Comment by Robinlovelace** [comment]
Work in progress: https://github.com/udsleeds/openinfra/pull/15

**Comment by Robinlovelace** [comment]
Map of that area according to OSM highway data.

![image](https://user-images.githubusercontent.com/1825120/143826320-cd8650f0-f33f-41ff-b68c-cd6f38c3f4db.png)

**Comment by Robinlovelace** [comment]
Starter for 10 on the OSM map...

![image](https://user-images.githubusercontent.com/1825120/143827294-bafa9f2d-96e4-4069-97e6-933379d6e58b.png)

**Comment by Robinlovelace** [comment]
A bit better...

![image](https://user-images.githubusercontent.com/1825120/143829636-41cce1b0-7bef-42f1-87d7-89adc08b3259.png)

**Comment by Robinlovelace** [comment]
Creating an A3 template in Gimp...

![image](https://user-images.githubusercontent.com/1825120/143830398-f6bf6000-0d9c-4500-8cf8-27d4b411e608.png)

**Comment by Robinlovelace** [comment]
Here's a starter on the ouput... https://github.com/udsleeds/openinfra/releases/download/v0.1/mcr.xcf

**Comment by GretaTimaite** [comment]
looks good for me. Would it be useful add a header above each image saying "osm', for instance?

**Comment by GretaTimaite** [comment]
I'm also wondering if we should add a QR code to the github repo (nad/or your Twitter) for those who want to learn more?
This should open the repo:
![repo_qr](https://user-images.githubusercontent.com/84614994/143835954-1a7c916d-88e4-47cf-84c2-ec39fc111201.png)

**Comment by Robinlovelace** [comment]
Great idea!

**Comment by Robinlovelace** [comment]
Next steps: 

- Add another map, I'm thinking A/B Street
- Add OS data? You up for downloading OS data and creating a map @GretaTimaite ?
- Add other things like the barcode and headers - you up for giving that a go also Greta? I'll update that map...

**Comment by Robinlovelace** [comment]
Currently looking to import Manchester centre into A/B Street for another OSM view.

![image](https://user-images.githubusercontent.com/1825120/143839772-eab62f97-fca8-4b60-9746-984f8cb7c8f3.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/143839823-5efb47a3-71e3-48be-a3e0-65cd1f0d491e.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/143840133-d7d633cf-20eb-4c94-9af9-3463631ed5b2.png)

**Comment by Robinlovelace** [comment]
Just hit an issue with A/B Street https://github.com/a-b-street/abstreet/issues/814

**Comment by Robinlovelace** [comment]
Central Manchester in A/B Street

![image](https://user-images.githubusercontent.com/1825120/143841455-236ae2cd-8c82-474a-bb06-de721e369e39.png)

**Comment by GretaTimaite** [comment]
> Next steps:
> 
>     * Add another map, I'm thinking A/B Street
> 
>     * Add OS data? You up for downloading OS data and creating a map @GretaTimaite ?
> 
>     * Add other things like the barcode and headers - you up for giving that a go also Greta? I'll update that map...

barcodes and headers - no problem at all.
I can try to download OS data but I've never worked with json... Gonna check it out right now and will let you know how it goes

**Comment by Robinlovelace** [comment]
Here's a minimum viable product (MVP). 
![mcr](https://user-images.githubusercontent.com/1825120/143842930-9d8d21c9-13ab-4c13-958e-ee09e8d93c25.png)

You can edit the png or if you install and want to use Gimp with this (should work, not sure): https://github.com/udsleeds/openinfra/releases/download/v0.1/mcr.xcf

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/143862999-8a1ec693-307d-45e9-b2e8-443ba6e41384.png)

**Comment by GretaTimaite** [comment]
Final A3
![poster](https://user-images.githubusercontent.com/84614994/143893998-7f05c8e3-bb2c-4301-9cc3-414632145ad5.png)

**Comment by Robinlovelace** [comment]
Great work @GretaTimaite !
