### ISSUE TITLE
CDRC presentation

### ISSUE THREAD

**Issue by GretaTimaite** [udsleeds/openinfra#19]
1 slide for the pres is needed. Maybe something like this?
<img width="960" alt="Screenshot 2021-12-13 at 16 41 15" src="https://user-images.githubusercontent.com/84614994/145853562-b9d6b56c-44c9-4da0-b9c4-c0893a2a2906.png">

Why I made it this way:

- I can mention the recategorization of OSM data
- lots of "maybe" which indicates a lack of data (tags) specifying if it's suitable for pedestrians
- LSOA coloured based on the number of individuals commuting to work on foot (2011 Census)
- red dots in the top left map show highways that have been tagged as wheelchair=yes
- a faceed bar charts borrowed from  #13 
---> good to demonstrate the potential of OSM

I was also thinking of making a .gif file instead of having 3 maps but if I include it with the faceted bar charts then it looks too much. Ideally I'd have less elements in this slide too, hence other options are:

a) focus on pedestrian_friendly = "yes"  & pedestrian_friendly = "maybe" because that's where the "gray" area is, in my opinion (I think I live this the most).
![Screenshot 2021-12-13 at 17 03 41](https://user-images.githubusercontent.com/84614994/145856530-fe3faa2b-dc02-42f3-b2dc-8bdff9e1c601.png)

b) exclude bar charts
![Screenshot 2021-12-13 at 17 04 01](https://user-images.githubusercontent.com/84614994/145856759-e567c98d-1a58-46b8-b859-98f12d72903a.png)

**Comment by GretaTimaite** [comment]
![Screenshot 2021-12-13 at 17 28 38](https://user-images.githubusercontent.com/84614994/145859998-6c602e92-f856-4dcc-be60-50b84e90bfc3.png)

**Comment by Robinlovelace** [comment]
Looking good!

**Comment by GretaTimaite** [comment]
Having interactive background makes the maps look less "flat"?
<img width="960" alt="Screenshot 2021-12-14 at 06 02 32" src="https://user-images.githubusercontent.com/84614994/145942312-c65d8fbb-1b92-41fc-aca3-17ab1c601f44.png">

Also uploaded [reproducible code](https://github.com/udsleeds/openinfra/blob/value-barplot/test-code/CDRC.R) (pls pull).

**Comment by Robinlovelace** [comment]
Nice! Yes interactive background looking good.
