### ISSUE TITLE
Scales in plots for GISRUK paper would be nice with % labels on Y axis

### ISSUE THREAD

**Issue by Robinlovelace** [udsleeds/openinfra#27]
Currently:

![image](https://user-images.githubusercontent.com/1825120/149766700-efe5bf3f-0aa9-4fbb-ae50-46b68814835e.png)

Example of future potential:

![image](https://user-images.githubusercontent.com/1825120/149766650-98113040-f32b-4ffe-9621-7f212c7a0d17.png)

**Comment by Robinlovelace** [comment]
On the case.

**Comment by Robinlovelace** [comment]
Work in progress

![image](https://user-images.githubusercontent.com/1825120/149767826-18a45047-46e2-4874-aa01-3ee48d24a100.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/149768160-5fd8a93f-6e6f-4919-b24c-de29248fa947.png)

**Comment by GretaTimaite** [comment]
true, it does look better. Just thinking that numbers in the plots could be rounded to one decimal place?

**Comment by Robinlovelace** [comment]
Good plan.

**Comment by GretaTimaite** [comment]
Just to check: you kept the numbers rounded to two significant numbers as it's not rounded to one decimal place in the script I have?

**Comment by Robinlovelace** [comment]
> Just to check: you kept the numbers rounded to two significant numbers as it's not rounded to one decimal place in the script I have?

Correct. I think to the nearest percent, e.g. 3% is fine but also happy with 1 d.p. e.g. 3.1%.

**Comment by Robinlovelace** [comment]
Additional issue: in Figure 1 the text showing % is above the lines

![image](https://user-images.githubusercontent.com/1825120/149810423-69639879-cbb1-4982-9634-8f943bd39fe3.png)

But in Figure 2 and other figures the text clashes: 

![image](https://user-images.githubusercontent.com/1825120/149810491-f984d930-590d-4f32-a9e2-7000a3312e2f.png)

I think this can help fix it, with `vjust` if I remember right: https://stackoverflow.com/questions/56816072/position-dodge-and-nudge-y-together

**Comment by GretaTimaite** [comment]
good point, checking it out rn

**Comment by GretaTimaite** [comment]
text and figures are not clashing in my rendered pdf but I did notice that some digits were "cut off" (look at the 6 in foot), so I reduced their size.
![Screenshot 2022-01-17 at 17 44 09](https://user-images.githubusercontent.com/84614994/149816955-c3cb8d02-11ea-47e4-9c9b-30127e6a1f3f.png)
![Screenshot 2022-01-17 at 17 36 39](https://user-images.githubusercontent.com/84614994/149815608-23d287e0-4926-431d-adc3-4c7cfe5a26f3.png)
