### ISSUE TITLE
Add content from old website readme into openinfra.Rmd

### ISSUE THREAD

**Issue by Robinlovelace** [udsleeds/openinfra#30]

**Comment by GretaTimaite** [comment]
I think this can be closed now as I've condensed this and added it [here](https://udsleeds.github.io/openinfra/articles/openinfra.html).

**Comment by Robinlovelace** [comment]
Great work Greta, took a look and big :+1: on this https://udsleeds.github.io/openinfra/articles/openinfra.html

I want to get the word out, you happy for me to Tweet about it (and are you Twitter/would like to be tagged or tweet it)?

**Comment by Robinlovelace** [comment]
> Also, thanks for asking but I don't have Twitter (this starts to become an inconvenience, tbh).
Could be a good excuse to get it : )
