### ISSUE TITLE
Statically hosted interactive web maps

### ISSUE THREAD

**Issue by Robinlovelace** [udsleeds/openinfra#31]
These could live on the openinfra website and look something like the maps here: https://www.cyipt.bike/rapid/west-yorkshire/ 

Instead of showing/hiding top ranked cycleways, different OSM data types could be selected and hidden:

![Peek 2022-01-28 12-49](https://user-images.githubusercontent.com/1825120/151549947-a47f4739-843f-4bc7-a446-13fa65576b2a.gif)

**Comment by Robinlovelace** [comment]
Code that generated that statically hosted multi-layered interactive map FYI: https://github.com/cyipt/popupCycleways/blob/master/code/build.R#L580-L612 

I don't recommend reproducing it but looking at it and creating your own interactive maps from the ground-up could be a good approach.

**Comment by hulsiejames** [comment]
Job done as shown in the screenshot: 

![image](https://user-images.githubusercontent.com/58815827/167402075-0bc46f02-89b5-44d8-81e2-ea9655b23a54.png)
https://udsleeds.github.io/openinfra/articles/getosm.html#interactive-maps-with-tmap-package

**Comment by hulsiejames** [comment]
Well done @GretaTimaite :tada:
