### ISSUE TITLE
vignette: getosm with R

### ISSUE THREAD

**Issue by GretaTimaite** [udsleeds/openinfra#34]
intro to getting and working with OSM data in R.

**Intro**:

- [x] why command line approach
- [x] purpose of the codebook
- [x] contents

**Downloading with `osmextract` package**:

- [x] why this package
- [x] demonstrate `oe_get()`
- [x] demonstrate `oe_get_network()`
------ [  ] in progress, see #32 
- [x] compare and contract both approaches
------ [  ] show how to filter out the dataset obtained using `oe_get` to get the same as you'd using `oe_get_network()` when the latter is fixed 
- [x] discuss tags 
- [x] show how to save as and load a dataset from the RDS file 

**Plotting**:

- [x] `plot()` for quick static maps
- [x] saving static maps 
- [x] `qtm()` for quick interactive maps
- [x] saving `qtm` maps

General stuff:

- [x] references in place
- [x] make sure code is well-commented
- [x] make sure all the datasets needed for this codebook is available to download as .Rds in case of need
- [x] include references to other resources (e.g., to geocomputation with R)
- [x] change file name to reflect the content better (e.g., "Getting and using OSM data with the R package osmextract")

Also to consider:

- [x] use only central Leeds instead of the whole Leeds to reduce the size of data
- [x] `download.file()` to solve `readRDS()` error

**Extensions of this vignette:**

- [x] OSM with Python
- [x] OSM with GUI

**Comment by GretaTimaite** [comment]
@Robinlovelace, it's a minor question so no rush to answer.

I'm making a point on static maps with `qtm()` vs `plot()` and I cannot find any arguments why one would insist on using `plot()` instead of `qtm()` for quick mapping that does not require any advanced control? It does not seem that qtm() takes longer to compute (at least for a dataset like Leeds). The only downfall is that `qtm()` requires and additional argument to get the legend.

**Comment by Robinlovelace** [comment]
This is basically done: https://udsleeds.github.io/openinfra/articles/osmintro.html

**Comment by Robinlovelace** [comment]
However, I think that that content should be in a vignette called Getting and using OSM data with the R package osmextract or similar, no?

**Comment by GretaTimaite** [comment]
Good point, I was going to change the file name today but forgot. I'll add that to the to-do list above and will come back to it tomorrow. I want to get some work done on #35 as it was neglected more than I'd like to.

**Comment by GretaTimaite** [comment]
@Robinlovelace I think this can be closed now?

**Comment by Robinlovelace** [comment]
This can be closed, great work!
