### ISSUE TITLE
vignette: what is osm?

### ISSUE THREAD

**Issue by GretaTimaite** [udsleeds/openinfra#35]
Not sure if this should be a separate vignette or combined with #34.

potential outline

**What is OSM:**

- [x] a few lines of its history and mission
- [x] focus on open-access + community-driven
----- maybe briefly mention how one can contribute to OSM? e.g. StreetComplete is a nice project 
- [x] discuss its structure
----- nodes, ways, relations, tags
- [x] add illustrations for each element
- [x] make a table outlining some tags that are easy to get started with and also make sure they are used in the upcoming vignettes.
- [x] add a map of tags for central Leeds

OSM + transport research

- [x] why useful to transport research 
- [x] how has OSM been used to plan transport network + infrastructure
------ [ ] A/B Street, CycleStreets
- [x] what gap does openinfra try to address?
----- [ ] improve accessibility to citizen and policy makers
----- [ ] explore its potential for accessible active travel planning  

General checks:

- [x] correct references
- [x] good labeling of images and plots

**Comment by Robinlovelace** [comment]
Looks like this will be a great article that many people could benefit from. Looking forward to reading it!

**Comment by Robinlovelace** [comment]
(And contributing to it.)

**Comment by GretaTimaite** [comment]
A thought as surfing literature: how useful would it be to have a curated (or not) OSM bibliography (not references used in a text) here? I.e., a list of introductory texts (such as [Haklay and Weber 2008](https://ieeexplore.ieee.org/abstract/document/4653466)), OSM + cycling, OSM+walking? I like good lists but not sure how useful/desired they are to others.

**Comment by Robinlovelace** [comment]
> A thought as surfing literature: how useful would it be to have a curated (or not) OSM bibliography (not references used in a text) here?

Useful, although most people will want to use our intro as a self standing introduction *from the perspective of the domain of transport planning*. Additional reading section idea: :+1:  from me!

**Comment by GretaTimaite** [comment]
Having GIFs like [here](https://labs.mapbox.com/mapping/osm-data-model/) to illustrate different data structures would be cool, I think. It just should be in the context of transport research. 

Potentially:

- nodes -> bus stops? or maybe bicycle parking? potentially [useful issue](https://github.com/osm-scotland/mappingedinburgh-issues/issues/59)
- ways -> cycleways
--------> not sure about polygons? maybe parks?
- relations -> route from a bicycle parking to a park?

Explain tags and the end to show how they help to represent the world.

I guess instead of Java OSM Editor I could use RStudio + interactive maps

**Comment by GretaTimaite** [comment]
So far [it's looking like this](http://rpubs.com/greta/864702). Not sure interactive maps are needed there? 

If needed, then I'd create a bounded box with the park in it only. Right now in the example I've provided in the document it's the whole Leeds. 

The idea for tags is to create a table with some tags (+ their meaning) that are important to get started with OSM + active travel. I think ideally these tags would be used in the follow-up vignettes, so there's consistency across them. The current candidates:

- highway
----->  I wonder if it needs a table of its own? If so, maybe I could borrow it from Chan and Cooper's paper. I also think that their road recategorization might be useful for others in their analysis 
- cycleway
- footway
- sidewalk
- width
- lit
- wheelchair
- maxspeed (?)

**Comment by GretaTimaite** [comment]
Thinking about the map that displays tags: should I leave "raw" OSM values or recategorize them? Or maybe we could have two maps? Kind of "before" and "after" we apply certain functions (when they are written) in the package to recategorize OSM data?

**Comment by GretaTimaite** [comment]
@Robinlovelace I'm wondering if I should focus on the UK as a case study when I discuss how OSM was used in transport research? My initial idea was yes, but the little problem is that I can find research on using OSM for cycling networks in the UK (e.g.,  Orozco et al.) but not for pedestrian networks. I note this in [the vignette](https://udsleeds.github.io/openinfra/articles/openinfra.html#osm-and-transport-research) but it ruins the structure + I'm just assuming that there's a lack... Maybe you've recently come across anything? I'm also trying to think about the projects that use OSM for pedestrian infrastructure planning or as a routing but originated from the UK.

So the question is: should I provide generic overview of OSM in TR or should I leave this assumption in the vignette?

P.S. looking into the error in the actions. Must be because I did a minor change yesterday in downloading a dataset.

**Comment by Robinlovelace** [comment]
Hi Greta, I'm not 100% sure what you mean. I do think a general introductory overview of OSM, that does not contain code, aimed at transport planners and transport policy makers interested in what it can (and cannot do) will be a unique and valuable contribution of the 'what is osm' article.

**Comment by GretaTimaite** [comment]
@Robinlovelace I think this can be closed now?

**Comment by Robinlovelace** [comment]
Sure, great work!
