### ISSUE TITLE
LCC footfall

### ISSUE THREAD

**Issue by GretaTimaite** [udsleeds/openinfra#43]
I think [LCC footfall data](https://data.cdrc.ac.uk/dataset/leeds-city-council-footfall-camera-aggregated-data) demands its own issue.

Initial idea: use it with OSM and `inclusive_mobility_get` function to find out if these spots are accessible. I think it would be a relevant case study because of how many pedestrians walk there. Also because it's a rather small dataset in terms of area coverage, it would be feasible to go out there to evaluate accessibility of those locations in person and, then, compare to computed results.

Screenshot of data structure:
<img width="897" alt="Screenshot 2022-03-29 at 16 10 46" src="https://user-images.githubusercontent.com/84614994/160653791-903d7abe-13bb-4fa6-af4a-b07d9c46aa53.png">

**Comment by GretaTimaite** [comment]
Checked out the pavement surface of the streets for which footfall data is collected.
![Screenshot 2022-05-17 at 06 58 29](https://user-images.githubusercontent.com/84614994/168739466-4312299c-961d-483a-b9cc-b209ef27403a.png)

Alas, not even one has data on tactile paving...

Code for all this can be found in the [R script for SOTM2022](https://github.com/udsleeds/openinfra/tree/main/sotm2022) (reproducibility has not been checked yet)

**Comment by Robinlovelace** [comment]
Nice!

**Comment by GretaTimaite** [comment]
I created a simple index from 0 (lowest) to 5 (highest). Here's the map:
![Screenshot 2022-05-17 at 08 50 15](https://user-images.githubusercontent.com/84614994/168758481-21e1130a-57bc-408b-8074-c602da56b487.png)

All of them scored at least 1 because there is info on them being a) footways b) footpaths c) implied footways. In general I think it's quite a nice way to show how much important data is missing.

**Comment by hulsiejames** [comment]
Greta in teams : "Basically I want to discuss IM + index and then move on to "further steps", ie scaling up."
reading : [SOTM Abstract](https://github.com/udsleeds/openinfra/blob/main/sotm2022/sotm2022.qmd )

Thoughts on the last few paragraphs (the most recently updated):
_______________________________
From my initial _blind_ reading (the position of the abstract reader I would imagine) of the paragraph introducing the IM function I didn't quite understand what it did  and I needed to have a play around in R to be sure even after reading the [function code](https://udsleeds.github.io/openinfra/articles/im_get.html). 

I know you mentioned that you would like a brief discussion on IM function + index and I do like the currently listed discussion and limitations of IM function but feel a brief overview sentence/example could provide some context, i.e.
 
"our IM function analyses OSM feature tags and compares these to relevant feature standards outlined by the IM guide to return whether or not the OSM feature analysed is indicative feature compliant with IM definitions, for example whether or not a feature surface is even or uneven (e.g. ease of use for wheelchair users) - additionally each feature is returned with an index rating of accessibility ranging from 0 to 5 with 0 implying no IM feature traits, to 5 implying full IM feature traits"

(if we run out of word count we could always remove limitations and stick with a description of IM + index? limitations etc could be talked about in a talk/workshop/etc. if needed)

__________________
" yet this is not directly compatible to OSM’s definition " **---** could we add the OSM definition for clarity and to highlight this (? word count permitting) which I assume is : "[minor pathways which are used mainly or exclusively by pedestrians](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dfootway). "
______________
"One potential application of the IM function could be to explore the existence and geographic distribution of accessibility indicators, such as the presence of a flush kerb." **---** really like this in terms of scaling up/ future work mention, "how IM friendly is your city currently?" & "which areas should you focus on developing IM?" would be answered by such application of the IM function
_________________________________________

Really like the discussion on further steps / scaling up and the general discussion on pros & cons IM function.

**Comment by GretaTimaite** [comment]
Thanks @hulsiejames for detailed comments.
I agree that I might need to add a sentence that describes the IM function in more detail It would help to make a case for how it adds (could add?) value.

Regarding this:
> could we add the OSM definition for clarity and to highlight this 
I was really thinking of doing this but I also realize it's a conference in which there will be plenty of OSM experts and practitioners, so I thought it might be a bit redundant? I think @Robinlovelace could help on this one.

Regarding scaling up: I'd be more than happy to hear what you and Robin have discussed so far so I could incorporate it in the "further steps" discussion, which would be the last paragraph of the abstract. I don't want to misrepresent or limit the scope of the project because if we get accepted, the talk would heavily draw on your work (super excited about this tbh)!

**Comment by GretaTimaite** [comment]
I think it can be closed as LCC data was used for SOTM2022.
