### ISSUE TITLE
No link to the GitHub repo from website

### ISSUE THREAD

**Issue by Robinlovelace** [udsleeds/openinfra#44]
Looking at another project it seems we need something like this in the DESCRIPTION:

```
URL: https://github.com/a-b-street/abstr,
    https://a-b-street.github.io/abstr/
BugReports: https://github.com/a-b-street/abstr/issues
```

Source: https://github.com/a-b-street/abstr/blob/main/DESCRIPTION

**Comment by GretaTimaite** [comment]
On that note, I'm surprised there's no link to the website on GH repo "Code" section. Should be added too otherwise nobody will find it when visiting the GH repo
