### ISSUE TITLE
Build failing due to Python dependency

### ISSUE THREAD

**Issue by Robinlovelace** [udsleeds/openinfra#52]

**Comment by Robinlovelace** [comment]
Good to see the issue closed from a commit message 🎉

**Comment by Robinlovelace** [comment]
> Should I delete failed workflow-runs in the GH Actions?

No it's good to have the failures and successes documented for future generations of data scientists/researchers/developers.

**Comment by hulsiejames** [comment]
> Good to see the issue closed from a commit message tada

Was a little pre-emptive but got there eventually!
