### ISSUE TITLE
Modelling World 2022

### ISSUE THREAD

**Issue by GretaTimaite** [udsleeds/openinfra#58]
Created this issue to discuss/track things needed for the conference.

**Comment by GretaTimaite** [comment]
To Juliana
- [ ] Abstract 1 (James, sesh 1)
- [ ] Abstract 2 (Greta, sesh 2)
- [ ] Which ticket to buy? Do presenters get a discount?

**Comment by hulsiejames** [comment]
Uploaded abstract with [eb7bfa8](https://github.com/udsleeds/openinfra/commit/eb7bfa8c641ba8ba3d863b02ffd5e319c739dfdb) and drafted e-mail for Juliana. Will send after confimation
