### ISSUE TITLE
Example datapack for Leeds

### ISSUE THREAD

**Issue by hulsiejames** [udsleeds/openinfra#59]
Create geojson object for leeds , upload as release. 

What are we keeping within these networks
 * walking networks
 * cycling networks
 * driving netwroks
 * all combined 
 * specific feature tags (max_speed etc.)

Additional thoughts and comments welcome

**Comment by Robinlovelace** [comment]
Looks good!

**Comment by hulsiejames** [comment]
UPDATE: 

@GretaTimaite, based on your comment I thought it would be a good idea to actually find out how each of the packages ([pyrosm](https://github.com/HTenkanen/pyrosm), [OSMnx](https://github.com/gboeing/osmnx), [osmextract](https://github.com/ropensci/osmextract)) define the pre-defined networks. 

I have created a draft .Rmd --> .html vignette that [I have hosted myself](https://hulsiejames.github.io/static_hosts/) (we can add here if not too large a file or too messy) which compares the tag filtering between the three packages. 

And, for osmextract, which seems to make queries directly to the API via SQL queries, I have translated SQL queries to a more human readable output and then (*tried for now*) to translate these into the python formats utilised by pyrosm and OSMnx. However I have had some dificulity making some of the python translations at the moment (specifically ones like "remove feature if tag highway=cycleway UNLESS feature also has tag foot=yes")

My plan is to essentially combine the "best of both worlds" tag:value filters from these three packages to define (*hopefully more accurate*) networks for the datapacks.

Looking into [LTN 1/20](https://www.gov.uk/government/publications/cycle-infrastructure-design-ltn-120) for more reference on defining cycling networks. 

I like the idea of mapping modal filters, but if our focus is on active travel networks (walking & cycling) then these are not of concern as these only affect the driving networks? 
Unless we think including general road networks within the datapacks too? (the other day I was able to define the bus routes throught the city of leeds)
![](https://i.imgur.com/z7JS1KN.png)

**Comment by Robinlovelace** [comment]
Looking like good progress. Having looked at your self hosted example, great to see it progressing. Have you checked the functions for downloading walking/cycling networks in `osmextract`? And I think that for some applications the columns available (set with `extra_tags` in `osmextract`) may be more important than which features are included.

In any case I think it would be great if this becomes a vignette. Sound like a plan James? Great work in any case!

**Comment by GretaTimaite** [comment]
@hulsiejames,

great stuff on the vignette comparing networks! Much needed even if laborious! It deffo should be a vignette on OpenInfra website.

> I have had some dificulity making some of the python translations at the moment 

We discussed this this morning but do let me know if you want to chat about it specifically (or create a new issue ;))

> I like the idea of mapping modal filters

I didn't mean that we needed to map modal filters. It was just something I've found when searching about LTN1/20. I'm wondering if it would make sense to contact Martin and ask how he's defined cycling network and maybe just try to translate his code/sql query to R/Python instead of trying to reinvent the wheel? 

Also, have you by any chance managed to contact Martin after MW22? He did offer us a free 2 day workshop on OSM, which I think shouldn't be missed.

**Comment by Robinlovelace** [comment]
A workshop or mini conference on OSM for active travel would be really useful.

**Comment by hulsiejames** [comment]
> @hulsiejames The osmextract filter issue resembles the issue #31 I had before, so I'd recommend reopening the old one to maintain consistency/coherent documentation of a problem. If it's unrelated then a new one can be created.
> 
> Good luck :)

Yup, I thought as much! 

Tomorrow morning I'm going to re-create your issue. If it still persists I'll re-open the old one and add my experience as an additional example. 

If the original issue has been fixed I'll just open a new one. (If this is the case I may also try with driving as I imagine this will have a similar issue. However not a focus as not active travel)

**Comment by Robinlovelace** [comment]
Yes we should submit a paper there for sure, great thinking Greta. Would you like to draft a structure/contents that could fit in well there? Excited about this, great new journal!

**Comment by GretaTimaite** [comment]
> Yes we should submit a paper there for sure, great thinking Greta. Would you like to draft a structure/contents that could fit in well there? Excited about this, great new journal!

I was thinking that it could be done after SOTM 2022 when I (and James) get more experience in this but I reckon I can start thinking + exploring what has been done/is being done in relation to it, so we can better contextualize our project. Going to create a new issue on this to keep me (us?) accountable.

**Comment by GretaTimaite** [comment]
No pressure (just a gentle nudge!) @hulsiejames but I still would like to try submitting a paper on OpenInfra to the [JOSIS special feature](http://liverpool.gisruk.org/call-for-papers-for-journal-of-spatial-information-science-josis-special-feature/) (deadline's 30 August) :) Your work will be critical but I'm here to help.

**Comment by hulsiejames** [comment]
Thanks @GretaTimaite I'll create a spereate issue for this so it's fresh in my mind! finishing off a `recode_road_class` function to get some data pack visualisations today!

**Comment by hulsiejames** [comment]
Definitive list of columns for data pack: 

build data pack script:

(ready to go | add quickly | would like to have evnetually) 

publically available links of public datasets - release datapack as a geosjon and release through releases
show reproducible documentation (vignettes) [what types of vignette would the group like to see]
try get some results for a couple of other areas. 

Kit (WY)


1. osm_id
2. highway
3. openinfra_highway (character string)
4. openinfra_max_speed
5. openinfra_active_travel (cycleway/footpath)
6. openinfra_IM
7. LTN1/20 compliance ~ (msg caroline tait).
8. Traffic_volume.
9. Potential light level or presence of light.

**Comment by GretaTimaite** [comment]
re:
> 5. openinfra_active_travel (cycleway/footpath)

I guess you can have a look into my IM function and join footpath, footway, and implied footway columns to come up with a single/complete "footpath" column.

I reckon cycleways could be "collected" in a similar way but altering walking-related tags to the cycling alternatives.

Additional thought: wouldn't it be good to indicate shared spaces too?

**Comment by GretaTimaite** [comment]
I might not have to remind you this but be attentive to implied values, eg as in surfaces (I've done this work, though, in the IM function, see surface column). Feel free to adapt it for your needs
![Screenshot 2022-03-15 at 10 30 41](https://user-images.githubusercontent.com/84614994/177138746-1f62f87a-b387-42c5-8995-a46774ac4dc8.png)

**Comment by hulsiejames** [comment]
Steering group meeting : 

Robin's comment

 - Implied max speed could be really useful. (implied from road description)
- FYI James I think we could use Google's Roads API to assess the accuracy of speed limit estimates: https://developers.google.com/maps/documentation/roads/speed-limits
__________________________________________
User testing - comments and suggestions

- what is the plan to test the data packs with aurhotities - get in contact and see what is required 
- what 'user testing' have we done (ensure we are using useful variables to local bodies). None! but some thoughts from discussion are... 
- General approach - include everything in a pack and then whittle down to baseline (thus finding most value added variables)
- Potential for a number of variations of datasets - Cycling dataset, walking dataset, minimal network dataset, data pack with all variables. send out and get feedback on each one? 
- No concrete user testing plans as of yet - discussed was to get a 2 stage testing process - key people we know (Kit WY authority) and then, later, maybe a bigger workshop (on basecamp?) pencil in a date and get a discussion rolling.  (Kayley digging out other names)
- 2/3 Week timeline for user training
_______________________________________________
Data pack geography level

- Datapacks at LAD level - highways level - multiple geographies! (james: Which do you think would be most useful?)
_____________________________________
Using openinfra functions in conjunction

- Examples on using combintations of cuntions
____________________________________
Academic credit adds backing to the work/data/outputs
- Publish the data - Get academic credit for it! (JSOS?)

**Comment by hulsiejames** [comment]
Going to close this now as we have a vignette showing off the example Leeds data pack.

This is going to be updated tomorrow (04/07/2022) and sent out in an email to partners so this vignette will always be the most up to date Leeds example data pack.

https://udsleeds.github.io/openinfra/articles/data_packs.html
