### ISSUE TITLE
Create and save test dataset representing cycleways in West Yorkshire

### ISSUE THREAD

**Issue by Robinlovelace** [udsleeds/openinfra#6]

**Comment by Robinlovelace** [comment]
Working on this with @GretaTimaite and @eugenividal

**Comment by eugenividal** [comment]
# Load data

## Load infras data
infras = readRDS("Data/ways_all.Rds")
## Create length_m variable
infras$length_m = as.numeric(st_length(infras))

## Load zone data
zm = readRDS("Data/zm.Rds")

# Aggregate cycling infrastructure into smaller categories
## Use wikipedia to stablish the categories. Different labels can be seen here.
https://wiki.openstreetmap.org/wiki/Bicycle#cite_note-anyroad-1.
## OSM distinguishes between cycle lanes and cycle tracks. A cycle lane lies within the roadway itself (on-road), whereas a cycle track is separate from the road (off-road).

## Extract cycleways highway dataset
i_cycle_tracks = filter(infras, highway == "cycleway") 
## Extract cycleways left or right dataset
i_cycle_lanes = filter(infras, (cycleway.left != "no" | cycleway.right != "no") & highway != "cycleway")

# Aggregate infrastructure variables to zm
# lads_imd$length_infras = aggregate(infras["length_m"], lads_imd, FUN = sum)$length_m
# Aggregate cycleways highway
lads_imd$length_cycle_tracks = aggregate(i_cycle_tracks["length_m"], lads_imd, FUN = sum)$length_m
# Aggregate cycleways left or right
lads_imd$length_cycle_lanes = aggregate(i_cycle_lanes["length_m"], lads_imd, FUN = sum)$length_m
