### ISSUE TITLE
GH actions failing after session this morning

### ISSUE THREAD

**Issue by hulsiejames** [udsleeds/openinfra#60]
GH actions are [failing](https://github.com/udsleeds/openinfra/runs/6657661201?check_suite_focus=true) after our coding session this morning @Robinlovelace on #56 

Seems to be failing due to the following error within `Run r-lib/actions/setup-r-dependencies@v1`
```
  Error: Error: <callr_remote_error: Cannot install packages:
  * MASS: Needs R >= 4.3>
   in process 9022 
  -->
  <simpleError: Cannot install packages:
  * MASS: Needs R >= 4.3>
```

Full details on `Run r-lib/actions/setup-r-dependencies@v1` below
<details>

```
Run r-lib/actions/setup-r-dependencies@v1
Run cat("::group::Install pak\n")
Install pak
Run cat("::set-output name=os-version::", sessionInfo()$running, "\n", sep = "")

Run actions/cache@v2
Received 121634816 of 248224025 (49.0%), 115.9 MBs/sec
Received 248224025 of 248224025 (100.0%), 117.7 MBs/sec
Cache Size: ~237 MB (248224025 B)
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/efc7ee09-1c0b-41b7-a1a6-06fabe7d74c2/cache.tzst -P -C /home/runner/work/openinfra/openinfra
Cache restored successfully

Cache restored from key: Ubuntu 20.04.4 LTS-R version 4.2.0 (2022-04-22)-1-3ee87c5ee5307601a2f33f13366ac29a59d84cffe7e8b1475daa459701f34202
Run cat("::group::Install dependencies\n")
Install dependencies
  ℹ Loading metadata database
  ✔ Loading metadata database ... done
  
  ℹ Executing `sudo apt-get install -y libcurl4-openssl-dev`
  ℹ Executing `sudo apt-get install -y libssl-dev`
  ℹ Executing `sudo apt-get install -y libudunits2-dev`
  ℹ Executing `sudo apt-get install -y libgdal-dev`
  ℹ Executing `sudo apt-get install -y gdal-bin`
  ℹ Executing `sudo apt-get install -y libgeos-dev`
  ℹ Executing `sudo apt-get install -y libproj-dev`
  ℹ Executing `sudo apt-get install -y zlib1g-dev`
  ℹ Executing `sudo apt-get install -y libicu-dev`
  ℹ Executing `sudo apt-get install -y make`
  ℹ Executing `sudo apt-get install -y libpng-dev`
  ℹ Executing `sudo apt-get install -y libxml2-dev`
  ℹ Executing `sudo apt-get install -y pandoc`
  ℹ Executing `sudo apt-get install -y libfontconfig1-dev`
  ℹ Executing `sudo apt-get install -y libfreetype6-dev`
  ℹ Executing `sudo apt-get install -y imagemagick`
  ℹ Executing `sudo apt-get install -y libmagick++-dev`
  ℹ Executing `sudo apt-get install -y gsfonts`
  ℹ Executing `sudo apt-get install -y libcurl4-openssl-dev`
  ℹ Executing `sudo apt-get install -y libssl-dev`
  
  Error: Error: <callr_remote_error: Cannot install packages:
  * MASS: Needs R >= 4.3>
   in process 9022 
  -->
  <simpleError: Cannot install packages:
  * MASS: Needs R >= 4.3>
  
   Stack trace:
  
   12. (function (...)  ...
   13. base:::withCallingHandlers(cli_message = function(msg) { ...
   14. get("pkg_install_make_plan", asNamespace("pak"))(...)
   15. prop$stop_for_solution_error()
   16. private$plan$stop_for_solve_error()
   17. pkgdepends:::pkgplan_stop_for_solve_error(self, private)
   18. base:::stop("Cannot install packages:\n", msg, call. = FALSE)
   19. base:::.handleSimpleError(function (e)  ...
   20. h(simpleError(msg, call))
   21. base:::stop(e)
   22. (function (e)  ...
  
   x Cannot install packages:
  * MASS: Needs R >= 4.3 
  
  Execution halted
  Error: Process completed with exit code 1.
```

**Comment by Robinlovelace** [comment]
Should be a self fixing bug. I bet other people are seeing this.

**Comment by hulsiejames** [comment]
Good to hear! Was worried I might have been using a different R version and that could be the issue. 

Will re-try these later on and then tomorrow and update.

**Comment by hulsiejames** [comment]
Updates: 
I've been trying to re-run all failed jobs a number of times the last couple of days however have had no luck.

I went to our [pkgdown.yaml](https://github.com/udsleeds/openinfra/blob/main/.github/workflows/pkgdown.yaml) and [R-CMD-check.yaml ](https://github.com/udsleeds/openinfra/blob/main/.github/workflows/R-CMD-check.yaml)and followed the link for [debugging build failures](https://github.com/r-lib/actions#where-to-find-help) and have noticed that
[/setup-r@v2](https://github.com/r-lib/actions/tree/v2-branch/setup-r), 
[/setup-r-dependencies@v2](https://github.com/r-lib/actions/tree/v2-branch/setup-r-dependencies), 
[/setup-pandoc@v2](https://github.com/r-lib/actions/tree/v2-branch/setup-pandoc) 
all have v2 versions available which are used in examples on the linked documentation pages, whilst we still use v1 for these. (We already use [checkout@v2](https://github.com/r-lib/actions/tree/v2-branch/check-r-package))

I also notice that within the setup-r@v2 basic example, a version of R can be specified
```
steps:
- uses: actions/checkout@v2
- uses: r-lib/actions/setup-r@v2
  with:
    r-version: '3.5.3' # The R version to download (if necessary) and use.
- run: Rscript -e 'print("hello")'
```
@Robinlovelace I'm not too sure if this is even relevant/helpful to the issue, I didn't want to go editing these files/configs not fully understanding what I'd be changing!

**Comment by Robinlovelace** [comment]
Maybe try re-running `usethis::use_github_actions()` type functions and see what happens.

**Comment by hulsiejames** [comment]
Tried the follwoing after looking at the [help documentation](https://usethis.r-lib.org/reference/github_actions.html): 

First I tried: 
```
> use_github_action(name = "pkgdown.yaml")
✔ Saving 'r-lib/actions/examples/pkgdown.yaml@v1' to '.github/workflows/pkgdown.yaml'
• Learn more at <https://github.com/r-lib/actions/blob/v1/examples/README.md>.
```
but contrary to the documentation on [`use_github_action` ](https://usethis.r-lib.org/reference/github_actions.html)(below) it has used yaml@v1 rather than yaml@v2
______________________________________________________________________________________
***name**
For use_github_action(): Name of one of the example workflows from https://github.com/r-lib/actions/tree/v2/examples. Examples: "pkgdown", "check-standard.yaml"."*
_______________________________________________________________________________________
I then noticed that `use_github_action` also accepts a full url link to a valid .yaml file
______________________________________________________________________________________
***url**
The full URL to a .yaml file on GitHub.*
______________________________________________________________________________________
As such, I re-tried using `use_github_action` specifying the full ulr to the raw [pkgdown.yaml@v2 file](https://github.com/r-lib/actions/raw/v2-branch/examples/pkgdown.yaml)


```
>  help("use_github_actions")

>  help("use_github_action")

>  use_github_action(name = "pkgdown.yaml", url="https://github.com/r-lib/actions/raw/v2-branch/examples/pkgdown.yaml")
Error: Can't parse the URL provided via `repo_spec`.

>  use_github_action(name = "pkgdown.yaml", repo_spec= "r-lib/actions", url="https://github.com/r-lib/actions/raw/v2-branch/examples/pkgdown.yaml")
Error in use_github_action(name = "pkgdown.yaml", repo_spec = "r-lib/actions",  : 
  unused argument (repo_spec = "r-lib/actions")

>  use_github_action(name = "pkgdown.yaml", repo_spec=r-lib/actions, url="https://github.com/r-lib/actions/raw/v2-branch/examples/pkgdown.yaml")
Error in use_github_action(name = "pkgdown.yaml", repo_spec = r - lib/actions,  : 
  unused argument (repo_spec = r - lib/actions)

>  use_github_action(name = "pkgdown.yaml", repo_spec=NULL, url="https://github.com/r-lib/actions/raw/v2-branch/examples/pkgdown.yaml")
Error in use_github_action(name = "pkgdown.yaml", repo_spec = NULL, url = "https://github.com/r-lib/actions/raw/v2-branch/examples/pkgdown.yaml") : 
  unused argument (repo_spec = NULL)

>  use_github_action(name = "pkgdown.yaml", url="https://github.com/r-lib/actions/raw/v2-branch/examples/pkgdown.yaml")
Error: Can't parse the URL provided via `repo_spec`.
>  use_github_action_check_release()
✔ Saving 'r-lib/actions/examples/check-release.yaml@v1' to '.github/workflows/R-CMD-check.yaml'
Overwrite pre-existing file '.github/workflows/R-CMD-check.yaml'?

1: No way
2: I agree
3: Absolutely not

> Selection: 2
• Learn more at <https://github.com/r-lib/actions/blob/v1/examples/README.md>.
```

However I kept getting errors about unused argument `repo_spec` which I could not understand or debug online.

Next I saw that `use_github_action_check_releases` seemed to install the latest version of R and ran the R-CMD-check, I ran this as can be seen in the code block above. 

I created a **backup of both of our existing workflow.yaml files** incase anything went very wrong. 

![](https://i.imgur.com/qHUQW1l.png)

After running this the the R-CMD-check.yaml was modified and I pushed to the repo: 

![](https://i.imgur.com/V5rfa3m.png)


Again, the resulting workflows [failed](https://github.com/udsleeds/openinfra/runs/6688956320?check_suite_focus=true) with the same error as before: 
```
  Error: Error: <callr_remote_error: Cannot install packages:
  * MASS: Needs R >= 4.3>
   in process 8678 
  -->
  <simpleError: Cannot install packages:
  * MASS: Needs R >= 4.3>
```
Within the [failed ](https://github.com/udsleeds/openinfra/runs/6688956320?check_suite_focus=true)workflow run, under the `Run r-lib/actions/setup-r@v1` section I noticed the following lines of interest. 
```
809 - /usr/bin/sudo gdebi --non-interactive /home/runner/work/_temp/r-4.2.0_1_amd64.deb

*unimportant lines*

936 -  Selecting previously unselected package r-4.2.0.
937 -  (Reading database ... 247999 files and directories currently installed.)
938 -  Preparing to unpack .../work/_temp/r-4.2.0_1_amd64.deb ...
939 -  Unpacking r-4.2.0 (1) ...
940 -  Setting up r-4.2.0 (1) ...
941 - 
942 - 
943 - Reading state information... Done
944 - /usr/bin/sudo ln -sf /opt/R/4.2.0/bin/R /usr/local/bin/R
945 - /usr/bin/sudo ln -sf /opt/R/4.2.0/bin/Rscript /usr/local/bin/Rscript
946 - /usr/bin/lsb_release --short --codename
947 - focal
```

Suggesting that R 4.2 is being installed which explains the R >= 4.3 requirement for MASS that is failing the workflow.

I was going to try and specify an R>=4.3 using the approach (below) from my previous update, however searching for the latest version of R revealed that 4.2 is the [most up-to-date](https://www.r-project.org/) :man_shrugging: 

```
steps:
- uses: actions/checkout@v2
- uses: r-lib/actions/setup-r@v2
  with:
    r-version: '3.5.3' # The R version to download (if necessary) and use.
```

**Comment by Robinlovelace** [comment]
Was worth a try! Not urgent I can take a look at some point but won't be until in a few weeks time but which point their may be upstream fixes.
