### ISSUE TITLE
SOTM 2022

### ISSUE THREAD

**Issue by GretaTimaite** [udsleeds/openinfra#61]
We were accepted to deliver a workshop at [SOTM 2022](https://2022.stateofthemap.org/). This issue has been created to discuss everything related to it.
![Screenshot 2022-05-28 at 21 00 22](https://user-images.githubusercontent.com/84614994/171132012-6e106e02-a264-477e-9003-53397735b60f.png)

**Comment by GretaTimaite** [comment]
Attending a course on teaching data science and AI and [mybinder](https://mybinder.org/) and [online course starter](https://github.com/ines/course-starter-r) came up. The latter might help to overcome the problem of attendees not having the software installed. So maybe it's something to experiment with, given we have time!

**Comment by Robinlovelace** [comment]
Binder is good, see here for example: https://twitter.com/robinlovelace/status/1531239439896391681

Also you guys should get Twitter and start tweeting about this stuff, deserves to be out there!

**Comment by GretaTimaite** [comment]
Update on the format:
> Please note that it will likely not be possible to use your own laptop
for live presentations. The university has a closed infrastructure for
live streaming and you will have to use their computers. In particular,
take this into account if you are planning any demos.
We're sorry for any inconveniences this causes. We're
still clarifying the details with the university and will
notify you once we know more. We therefore ask you this year to
upload your slides (ideally in PDF format) and other material that you
need during your presentation to Pretalx some time before your talk so
we can copy everything to the university PC in time. In Pretalx,
resources like slides can be uploaded in the "Content" section of your
submission, next to the "Resources" item.

**Comment by GretaTimaite** [comment]
Also still waiting to hear about the academic track one...

**Comment by GretaTimaite** [comment]
Academic track update @Robinlovelace  @hulsiejames :)
![Screenshot 2022-06-27 at 14 01 44](https://user-images.githubusercontent.com/84614994/175947916-0e21bc28-4dab-45c4-bde8-38c711568327.png)
![Screenshot 2022-06-27 at 14 03 01](https://user-images.githubusercontent.com/84614994/175948047-e80d8e13-d148-43c4-bed1-3885790359da.png)

**Comment by Robinlovelace** [comment]
Fantastic, thank you Greta! I'm going to register before 1st July : )

**Comment by GretaTimaite** [comment]
I will not paste the full reviews here lest it's not ethical but my thoughts as of now are:
1. >  it would be helpful if authors could provide some examples or application scinerio how the OpenInfra can be used for better transportation planning in more details.

I see this as a valid point but also we are limited by a word count, hence I think it is something we could discuss in more depth in the presentation. Unless you come up with a clever way of adding this without compromising the entire abstract :)
 
2. > minor weakness I see in the abstract is the lack of a rigorous structure, based on the identification of a problem and then the presentation of a methodology and results to address it. Instead, the abstract describes different strands of activities (...)  while all of them are very clear, the reader may feel a bit lost when trying to link them into a common ‘journey’. 

Again, I think it's a valid point, however my initial idea was to engage a reader with OpenInfra project and what we do instead of focusing on one research problem. I did not want to duplicate myself by being too close to my GISRUK abstract and I did not think I have enough things to say about the index to make it a focal point. Again, I don't think we have much space/time to restructure the abstract but sometimes an added sentence or two can make a world of a difference! Feel free to shoot ideas if any.

3. > when you discuss the calculation of an index of accessibility, you first say that values range from 0 to 5 but then in the examples you used 0 and 1 and then you say that the maximum value is 2, which is a bit confusing.

I will look at that passage again as I agree it can be confusing and I might want to edit it. Here's what's in the abstract:
> 5 unique streets were identified, which resulted in 35 linestrings in OSM. Then, a basic index of accessibility, ranging from 0 to 5, was created. For example, if a linestring is classified as a footway, footpath, or implied footway based on the IM guide, then it received 1, otherwise 0. If a flush kerb is mapped, it received 1, otherwise (e.g., not flush or NA), 0 is given. Finally, the values were added and a final index produced. Following this, the highest index score is 2 (19 linestrings), while the rest scored 1. 

What I tried to say: I have discussed 0s and 1s in a sense of it being FALSE OR TRUE when meeting a given condition (e.g., im_kerb == "yes") while 1s and 2s are aggregate counts (out of 5). Let me know what you think or make direct edits to the file.

4. > number of references provided could be probably reduced, especially considering the limited length of the abstract allowed in the proceedings (if accepted). 

Will need your help on this one because you know I am a big fan of referencing and saying no to some of them is hard, especially that I did remove a few because of the reference limits imposed by the SOTM in the first place!

I think these are the main comments we have to consider but if there's anything else, bring them up :)

**Comment by hulsiejames** [comment]
> What I tried to say: I have discussed 0s and 1s in a sense of it being FALSE OR TRUE when meeting a given condition (e.g., im_kerb == "yes") while 1s and 2s are aggregate counts (out of 5). Let me know what you think or make direct edits to the file.

I suppose this could be re-written as: (excluding my comment [] this is 87 words)

"
We defined five indicators to accessibility, if a piece of infrastructure meets all five indicators it receives an accessibility index of 5, for every indicator missing the score drops by 1.  
For example, if a linestring classifies as a footway, footpath or implied footway (based on IM guide) [*I assume one of your 5 indicators is highway=c("footway", "footpath", "implied footway")*] then the linestring receives +1, if the linestring is also mapped as being a flush_kerb then the linestring recives +1 totaling +2.  
If none of the others conditions were met, the final accessibility score for this infrastructure is 2.
"


Maybe this provides a bit more context and shows that although the theoretical maximum is 5, the score is added iteratively for each indicator the features matches, and so five is an optimal score, and less common. 

Of course, this implies that there are five defined categories we *assess* accessibility for [2 I assume are `kerb_flush="yes"`, and `highway %in% c("footway", "footpath", "implied footway")` ] and I don't know if it would be expected for us to include all five defnintions (I would think so), but with pressure on wordcount, is this example is enough to show the concept and further and that an accessibility score is obtained if a criteria is matched, and then any questions can be asked after the talk/presentation etc?

Just my thoughts, maybe nonsense, but I hope is useful!

**Comment by GretaTimaite** [comment]
@hulsiejames and @Robinlovelace see my edited paragraph on the index (also a commit above):
> One potential application of the IM function could be to explore the existence and geographic distribution of accessibility indicators, such as the presence of a flush kerb. Yet, more interesting results can be produced by using recategorised OSM data in conjunction with other datasets that would help to improve the understanding of street accessibility. As an illustration for this, an open-access Leeds Central Council Footfall data was used [@footfall_data2021]. We reasoned that the locations at which footfall data was collected are heavily used by pedestrians, thus demonstrating the need to ensure inclusivity of spaces. 5 unique streets were identified, which resulted in 35 linestrings in OSM. Then, a basic index of accessibility, defined by 5 indicators, was created. If a street meets all 5 requirements, it receives a maximum index of 5; for every missing indicator the score is dropped by 1. For example, if a linestring classifies as a footway, footpath, or implied footway based on the IM guide then it receives +1. If it also has an even surface, it receives an additional +1, thus totaling to +2. If none of the other conditions are met then the final index score is 2. Following this, 19 out of 35 mapped linestrings scored 2 while the rest had an index of 1. This example does not necessarily show that the streets are inaccessible because the missing data make it hard to make a fair judgement (e.g., in this case not a single linestring has data on kerbs). However, we would argue that this is a space for OSM to produce more readily actionable insights regarding transport infrastructure, especially if joined with other (open) datasets that would help to overcome some of its current data limitations. 

Is it understandable? Also thinking that:
1.  the first two sentences are too similar
2. do I need to give an example to "current data limitations" which I use to finish the paragraph? I discuss in length the issue of missing data, so my hope is that a reader understands that I talk here about joining with datasets that would help to overcome an issue of missing sidewalk width data. Yet, I'm personally not sure where it could come from.

**Comment by GretaTimaite** [comment]
You can see a formatted (?) abstract here: https://docs.google.com/document/d/1ishwhuPAieFNSPD5STpq1D0kLhFOYdx5/edit?usp=sharing&ouid=112304654978716003137&rtpof=true&sd=true

You should only be able to comment. A couple of pain points:
1. SPACING! It looked ok in my docx version but once moved to Google Docs it got ugly again. I am thinking of emailing them and asking if we could insert a hyperlink. 
![Screenshot 2022-06-30 at 21 12 02](https://user-images.githubusercontent.com/84614994/176769214-1bc3eb66-c8bd-4372-affe-75a4f206df7c.png)
2. Figure. Do we want to insert one? If so, what? This one (see #43 as well)
![image](https://user-images.githubusercontent.com/84614994/176770346-90d70982-488a-48ba-a224-ffdcd40afc00.png)

**Comment by Robinlovelace** [comment]
Idea for figure:

![image](https://user-images.githubusercontent.com/1825120/176778969-a27330e6-8e8b-41fd-9467-1f7ddec48e2d.png)

**Comment by GretaTimaite** [comment]
Sorry but a no from me because this is not being discussed in the abstract, so I think it would be out of place even if it's pretty.

**Comment by Robinlovelace** [comment]
OK fair enough.

**Comment by Robinlovelace** [comment]
Reproducible example:

```
remotes::install_github("udsleeds/openinfra")
library(openinfra)
u_data_large = paste0("https://github.com/udsleeds/openinfra/releases",
"/download/v0.2/bbbike_leeds_27_6_22.geojson")
example_data = sf::read_sf(u_data_large)
library(tmap)
tm_shape(output %>% dplyr::select(road_desc)) +
  tm_lines(col = "road_desc", title.col = "Road class") +
  tm_layout(legend.bg.color = "white")
```

**Comment by GretaTimaite** [comment]
Something like this @Robinlovelace @hulsiejames ?
![Screenshot 2022-07-01 at 08 15 36](https://user-images.githubusercontent.com/84614994/176844250-0816eb73-9fa0-4b69-a9a4-dff37299fb83.png)

**Comment by GretaTimaite** [comment]
maybe without frame is better 
![Screenshot 2022-07-01 at 08 18 51](https://user-images.githubusercontent.com/84614994/176844571-19c9d797-0322-46ec-a724-ad815d9cf2af.png)

**Comment by GretaTimaite** [comment]
with a kerb mapped to show low number of tags being added that are essential for inclusive planning
![Screenshot 2022-07-01 at 08 36 09](https://user-images.githubusercontent.com/84614994/176847508-0d8d0b9b-3e24-4eb8-b707-4aeb5bf9470c.png)

**Comment by GretaTimaite** [comment]
google docs here: https://docs.google.com/document/d/1yJHeUFSMbmnED56C16e8TM8LpDDl4AJh/edit#

**Comment by GretaTimaite** [comment]
Referenced Figure 1 here in the abstract: 
> One potential application of the IM function could be to explore the existence and geographic distribution of accessibility indicators, such as the presence of footpaths, footways or flush kerbs (see Figure 1).

**Comment by hulsiejames** [comment]
> with a kerb mapped to show low number of tags being added that are essential for inclusive planning ![Screenshot 2022-07-01 at 08 36 09](https://user-images.githubusercontent.com/84614994/176847508-0d8d0b9b-3e24-4eb8-b707-4aeb5bf9470c.png)

I like this one, expecially with the addition of mapping flush_kerb, it fits well with your reference to it.

**Comment by Robinlovelace** [comment]
Great work @GretaTimaite we can close this issue now I think!

**Comment by hulsiejames** [comment]
> Thanks @hulsiejames, I think I like it most as well.
> 
> EDIT: also apologies for pushing all those edits -- I forgot its failing. Will stop now.

Look great @GretaTimaite! I will give you the satisfaction of closing :D
