### ISSUE TITLE
JOSIS special feature 

### ISSUE THREAD

**Issue by hulsiejames** [udsleeds/openinfra#66]
[JOSIS](http://liverpool.gisruk.org/call-for-papers-for-journal-of-spatial-information-science-josis-special-feature/) submission deadline 30th August

**Comment by Robinlovelace** [comment]
I've created a template for this: https://github.com/robinlovelace/rticles/tree/josis

**Comment by Robinlovelace** [comment]
You can install this specific version of rticles to get this nice template using this line of code (in context of the full paper): https://github.com/zonebuilders/zonebuilder/blob/1d3b16deb5db262fcc47426030a915032e17865c/vignettes/paper.Rmd#L76

**Comment by GretaTimaite** [comment]
I don't think we can write it up in a week. Close the issue @hulsiejames?

**Comment by Robinlovelace** [comment]
We could ask for an extension, nothing like a deadline!

**Comment by GretaTimaite** [comment]
We can email and ask about an extension, but I won't be able to work much (or offer support) on the article in the next 2 weeks. Would it be sensible to submit an article for the next issue rather than a special feature?
