### ISSUE TITLE
transport data packs: openinfra_active_travel 

### ISSUE THREAD

**Issue by hulsiejames** [udsleeds/openinfra#75]
My plan for 5. (openinfra_active_travel (cycleway/footpath)) was to create two columns (oi_active_cycle & oi_active_walk) which would contain values "yes" - "no" whether or not each feature within a network is part of a walking network, or cycling network.

That way, people can plot, say `plot(data_pack["oi_active_walk"] == "yes")` to visualise the infrastructure and view gaps.  

As suggested by @GretaTimaite in #59 - From the IM function I am collecting three categories to create oi_active_walk - footway, footpath & implied footway. 

Within [IM](https://udsleeds.github.io/openinfra/articles/im_get.html) docs, I have a way of combining footways & footpaths together and was looking at implied_footway column.

implied footway is defined as: 
```
dplyr::mutate(im_footway_imp = dplyr::case_when(
      im_footway %in% "no" &
        im_footpath %in% "no" &
        im_crossing %in% "no"
      ~ "yes",
      TRUE ~ "no"
```
 Implying that if a feature has no specified footway or footpth or crossing - it is implied that a footway is there anyway, which confused me as I thought that every feature within the network that has "no" for `im_footway` `im_footpath` & `im_crossing` will be classified as implied_footway, which is not always true. 

From Greta
> I think it does classify as such because it is implied that every street has a sidewalk. But since it’s not explicitly specified, I mark it as implied. Martin said he’d go for implied footways as ‘yes’ in footways (hence, eliminating the need for an implied column) but I want to highlight this uncertainty in data, which might be essential when planning.

I agree that we should not just include implied_footways as "yes" in footways as we should be highlighting the uncertainty of the data, especially if it is to be used as evidence.

**Comment by hulsiejames** [comment]
Adding to this - I now plan to have two columns for oi_active_walk --> oi_active_walk & oi_active_walk_imp so that we can explicitly metnion the assumption that most streets will have a sidewalk, but this is not always the case. 

As OSM mappers update the missing tags (which is why we need implied_footway) more featurres will move from oi_active_walk_imp to oi_active_walk as the data packs are updated.

**Comment by hulsiejames** [comment]
> so that we can explicitly mention the assumption that most streets will have a sidewalk, but this is not always the case.

For example - rail tracks are returned as im_footway_imp == "yes" as they are "no" for im_footpath, im_footway & im_crossing. 
There is a simple fix for this - specifying `total_place = total_place %>% filter(!is.na(highway))` so that only roads are entered into IM function

**Comment by hulsiejames** [comment]
Looking further. Provided that `total_place = total_place %>% filter(!is.na(highway))` is specified so that non-road features are removed, `oi_active_walk` column can be features that have im_footway_imp == "no", as if this is the case either `im_footpath` or `im_footway` are "yes"

**Comment by GretaTimaite** [comment]
Hi @hulsiejames, sorry for a delayed reply -- I got a bit busy. I added to my to-do list this issue as a first thing to do tomorrow morning. 

But a quick point:
 
I did not intend an im_function to be that generic as to define a, for instance, walking network for them within a function before creating new columns. Indeed, in my documentation I filter out some columns before proceeding to showing the function itself. So I assume that users define their own network before using the function, maybe it needs highlighting in the documentation:
```{r}
wy_lines_short = wy_lines %>% select(-c("waterway",  "aerialway", "z_order"))
```
I don't know where railways come up specifically as I don't see them in the default columns returned by the osmextract:
```{r} 
[1] "osm_id"     "name"       "highway"    "waterway"  
 [5] "aerialway"  "barrier"    "man_made"   "z_order"   
 [9] "other_tags" "geometry"
```
So it might have come from pyrsom and osmnx, but do let me know if I overlooked something.

Also, of course, an additional line filtering out rows with NA highways can be added

**Comment by GretaTimaite** [comment]
@hulsiejames, I'm reading your comments and I have the following points/questions:
 1. 
> Implying that if a feature has no specified footway or footpth or crossing - it is implied that a footway is there anyway, which confused me as I thought that every feature within the network that has "no" for im_footway im_footpath & im_crossing will be classified as implied_footway, which is not always true.

The focus should be on "not always true". I think the code shows that "every feature within the network that has "no" for im_footway im_footpath & im_crossing will be classified as implied_footway"? Why is it not always true? Implied alludes to uncertainty, thus all the certainty is captured before classifying a highway as having an implied sidewalk. 

2. 
> I now plan to have two columns for oi_active_walk --> oi_active_walk & oi_active_walk_imp so that we can explicitly mention the assumption that most streets will have a sidewalk, but this is not always the case.

I assume the same questions regarding implied access is relevant to cycling. I am not an expert in this area.

3.
> rail tracks are returned as im_footway_imp == "yes" as they are "no" for im_footpath, im_footway & im_crossing.

I think this was answered in my yesterday's comment? There is an assumption of a user pre-defining their walking network before applying the function.

4.
> oi_active_walk column can be features that have im_footway_imp == "no", as if this is the case either im_footpath or im_footway are "yes"

Again, sorry, I'm not following you here. Feel free to direct me to code as it might help.

**Comment by GretaTimaite** [comment]
Also, it got me thinking that it might be useful to differentiate between network and infrastructure. Based on my understanding a network just indicates the possibility of moving from point A to point B while infrastructure is more about who and how can move from point A to point B. Thus, in the case of, for instance, `oi_active_cycle` it would show a network rather than an infrastructure. This is fine too and I guess a focus on LTN1/20 would help to bring infrastructure back to focus.

Maybe @Robinlovelace can give his two cents on this transport network vs transport infrastructure difference, if there's one (I have not specifically explored literature on this, so my bad).

**Comment by Robinlovelace** [comment]
I think that a transport network is composed of features representing infrastructure so they can kind of be the same thing. In terms of what we call it, open minded, any concrete proposals welcome but don't think its a huge deal, main thing is the contents of the data and keeping it simple. Interested to hear thoughts on what we call them, given that we're talking about infrastructure data packs infrastructure data representing a transport network seems like a reasonable way to put it.

**Comment by hulsiejames** [comment]
Don't worry @GretaTimaite I'm still exploring and will update more as I do. Will try and find some examples but most of ym confusion has gone I think

I understood that you defined the network before using the function as in the documentation - my confusion was more in reference to the comment in #59. but I think this has been cleared up! 

> I guess you can have a look into my IM function and join footpath, footway, and implied footway columns to come up with a single/complete "footpath" column.
I reckon cycleways could be "collected" in a similar way but altering walking-related tags to the cycling alternatives.

**Comment by GretaTimaite** [comment]
@hulsiejames let me know if those railways come up from wy_joined. Also feel free to suggest changes in the vignette. As you can see it's still using RDS rather than geojson files, hence needs updating. There is "Notes" section listing what I meaning to do as well...

Also the data needs to be fixed. For example, lamp can be mapped as a node `highway=street_lamp` or an additional `lit=*` tag can be added. I commented out point data in the function when recategorising lighting, hence it is likely that point data (here: wy_points) are not relevant anymore (I don't recall if I use point data for crossings"). 

I'll add as my to-do for the next week or two to update this vignette.

**Comment by GretaTimaite** [comment]
Thanks for bringing this up. I just drop column names instead of filtering them out (back to that "not pre-defining networks" thing) so it makes sense that it remains as it's a linestring, a feature that I ask for in my osm query. I will make sure this is even more highlighted. Indeed, incorporating an example might be useful.

**Comment by hulsiejames** [comment]
I think this can be closed now with the additions of [oi_active_walk()](https://udsleeds.github.io/openinfra/reference/oi_active_walk.html) & [oi_active_cycle()](https://udsleeds.github.io/openinfra/reference/oi_active_cycle.html)
