### ISSUE TITLE
R-spatial learning

### ISSUE THREAD

**Issue by GretaTimaite** [udsleeds/openinfra#8]
The aim of this session is:

- [x] buffer around (pedestrian) infrastructure in WY
- [x] recategorise OSM's pedestrian infrastructure (`traffic calmer` package)
- [x] spatial join: OSM and administrative zones

**Comment by Robinlovelace** [comment]
Regarding recategorising columns, you could try making a function that returns an OSM data frame with a new variable called 'pedestrian' that is 'yes/no/maybe'. Starting point:

```r
tc_recode_speeds_uk = function(
  x,
  allowed_values = c("20 mph", "30 mph", "40 mph", "50 mph", "60 mph", "70 mph"),
  pattern = c("national" = "60 mph", "0$" = "0 mph")
  ) {
  sel_allowed = x %in% allowed_values
  x[!sel_allowed] = stringr::str_replace_all(x[!sel_allowed], pattern)
  x[!x %in% allowed_values] = NA
  x
}
```

Source: https://github.com/saferactive/trafficalmr/blob/master/R/tc_recode.R

**Comment by Robinlovelace** [comment]
Usage would be something like `recode_pedestrian(osm_data_frame)` and then it returns a data frame with the pedestrian column.

**Comment by Robinlovelace** [comment]
```r
  # bit that changes the outcome
  x$pedestrian = "yes"
  x$pedestrian[x$highway == "motorway"] = "no"
  x$pedestrian[x$highway == "cycleway" & is.na(x$foot)] = "maybe"
```

**Comment by Robinlovelace** [comment]
https://geocompr.robinlovelace.net/spatial-operations.html#spatial-joining

**Comment by Robinlovelace** [comment]
We also discussed Git workflow. Conceptual diagram of the approach created during the session today:

![image](https://user-images.githubusercontent.com/1825120/142629814-05688246-5ee7-43df-bfa9-3e8f2b88dfaa.png)

Source: https://excalidraw.com/#room=e6135fdcba9f0a0dc2c5,3b8xn_OIVlLJehZ-9KbOVA

**Comment by GretaTimaite** [comment]
joined leeds_pct with census (2011) data on traveling on foot (%) 
<img width="640" alt="Screenshot 2021-11-23 at 08 21 02" src="https://user-images.githubusercontent.com/84614994/142979073-0d150d48-1e8b-4702-aa8d-30bfc1ab8904.png">

Also plotted it with osm's highway="footway"
<img width="608" alt="Screenshot 2021-11-23 at 08 20 00" src="https://user-images.githubusercontent.com/84614994/142979161-50acf960-d56c-43f8-94fc-1722fcd90782.png">

Going to work on [economic activity](https://observatory.leeds.gov.uk/economy-and-employment/map/) and then will move to the pedestrian infrastructure.

**Comment by GretaTimaite** [comment]
update on "economically active": 
<img width="699" alt="Screenshot 2021-11-23 at 08 58 35" src="https://user-images.githubusercontent.com/84614994/142982353-7ab00c5b-3729-46d5-bc07-4ae37d1b2130.png">
<img width="441" alt="Screenshot 2021-11-23 at 08 58 57" src="https://user-images.githubusercontent.com/84614994/142982366-d22cb453-d9cd-4522-9b3b-e0593cab7049.png">

I'm surprised that center of Leeds has such a low number of economically active individuals (which actually [includes not](https://observatory.leeds.gov.uk/economy-and-employment/) only those who are in full/part-time employment but also those searching for a job). 

Based on a quick visual examination, the least economically active LSOAs seem to (partially) overlap with the highest level (%) of traveling to work on foot. I'd say it's pure convenience to walk to work if you live in the city centre but maybe it is also a factor that contributes to more extensive mapping? For example, let's *assume* that those living in the central Leeds occupy higher socioeconomic status and that OSM mappers tend to be members of the middle/higher socioeconomic class (it was mentioned somewhere, I think in Haklay's (2010) paper?). Then, if they choose to travel to work on foot, they might be more likely to pay more attention to walking infrastructure, which then contributes to the area being mapped more extensively. Of course, it's not the sole (or even main) reason but maybe something to think about...

**Comment by GretaTimaite** [comment]
> joined leeds_pct with census (2011) data on traveling on foot (%) <img alt="Screenshot 2021-11-23 at 08 21 02" width="640" src="https://user-images.githubusercontent.com/84614994/142979073-0d150d48-1e8b-4702-aa8d-30bfc1ab8904.png">
> 
> Also plotted it with osm's highway="footway" <img alt="Screenshot 2021-11-23 at 08 20 00" width="608" src="https://user-images.githubusercontent.com/84614994/142979161-50acf960-d56c-43f8-94fc-1722fcd90782.png">
> 
> Going to work on [economic activity](https://observatory.leeds.gov.uk/economy-and-employment/map/) and then will move to the pedestrian infrastructure.

just to note that this is traveling TO WORK on foot.

**Comment by Robinlovelace** [comment]
This is really good stuff. Keep up the great work @GretaTimaite !

**Comment by GretaTimaite** [comment]
I've finished recategorizing pedestrian network (but not accessibility!) but it is yet to be turned into a function
It looks like this

```{r}
wy_walking_fr <- wy_walking %>% 
  mutate(pedestrian_friendly = case_when(
    highway %in% highway_pedestrian_yes ~ "yes",
    highway %in% highway_pedestrian_no ~ "no",
    
    highway %in% highway_pedestrian_maybe & 
      foot %in% foot_pedestrian_yes | 
      footway %in% footway_pedestrian_yes | 
      sidewalk %in% sidewalk_pedestrian_yes |
      pedestrian %in% ped_pedestrian_yes |
      path %in% path_pedestrian_yes
    ~ "yes",
    
    highway %in% highway_pedestrian_maybe |
      foot %in% foot_pedestrian_maybe |
      footway %in% footway_pedestrian_maybe # note: there's no "maybe" sidewalk
    ~ "maybe",
    
    highway %in% highway_pedestrian_maybe & 
      foot %in% foot_pedestrian_no  | 
      footway %in% footway_pedestrian_no | 
      sidewalk %in% sidewalk_pedestrian_no |
      path %in% path_pedestrian_no
    ~ "no"
         )
         )
```

Here's the recategorized pedestrian network in Leeds, which was filtered by `pedestrian_friendly == "yes"`
<img width="441" alt="Screenshot 2021-11-24 at 14 19 04" src="https://user-images.githubusercontent.com/84614994/143237197-1fc8ca46-c0c1-46a4-b284-ef31bb05a227.png">

I've compared WY to GM but for that see #11

**Comment by Robinlovelace** [comment]
Good progress. I would like to see some Google Earth or StreetView images of places that are deemed to be 'pedestrian friendly' and not as a sense check.

**Comment by GretaTimaite** [comment]
> Regarding recategorising columns, you could try making a function that returns an OSM data frame with a new variable called 'pedestrian' that is 'yes/no/maybe'. Starting point:
> 
> ```r
> tc_recode_speeds_uk = function(
>   x,
>   allowed_values = c("20 mph", "30 mph", "40 mph", "50 mph", "60 mph", "70 mph"),
>   pattern = c("national" = "60 mph", "0$" = "0 mph")
>   ) {
>   sel_allowed = x %in% allowed_values
>   x[!sel_allowed] = stringr::str_replace_all(x[!sel_allowed], pattern)
>   x[!x %in% allowed_values] = NA
>   x
> }
> ```
> 
> Source: https://github.com/saferactive/trafficalmr/blob/master/R/tc_recode.R

Just finished writing recode_pedestrian() function. [It's here](https://github.com/udsleeds/openinfra/blob/region-name-rl/test-code/recode_pedestrian_function.Rmd). I'm yet to test all the arguments, but seems to be working in general. Let me know your thoughts

**Comment by Robinlovelace** [comment]
I think you've done a great job and that this issue can be closed. No time to test the function but will do next week.
