### ISSUE TITLE
ResCompLeedsCon2022 

### ISSUE THREAD

**Issue by hulsiejames** [udsleeds/openinfra#80]
We have been accepted for a 10 minute research story talk at [ResCompLeedsCon2022!
](https://rescompleedscon.github.io/conference2022/schedule/#session-2702)
- Talk title: OpenInfra - open access data for transport research: tools, modelling, and simulation

- Talk format: 10 minute talk

- Talk day: 27th July

- Talk start time: 1300

- Talk room: Worsley 8.43X and Y, Level 8, Worsley Building

**Next Steps**
- Submit small bibliography and photo fortalk speakers
- Submit your slides by Friday 22nd

**Comment by GretaTimaite** [comment]
Congratulations @hulsiejames! Any update on the slides? Are you thinking of reusing the ones from LIDA Seminar Series?

**Comment by hulsiejames** [comment]
> Congratulations @hulsiejames! Any update on the slides? Are you thinking of reusing the ones from LIDA Seminar Series?

Woorking on them now - a similar format but more updated content! Should be appropriate as the talk is around 10 minutes and so is our slot for this conference!

**Comment by GretaTimaite** [comment]
OK, let me know if you want me to look at them (or practice a presentation a few times) before you submit them

**Comment by hulsiejames** [comment]
Presentation: https://www.youtube.com/watch?v=N31vUTJA31s (first 8 minutes)

Unfortunately, tech was not on our side for the presentation recording, as the slideshow was not captured in the recording and it starts on slide 5! 

I may re-do this at another point so we can add a recording to the website. (I wanted to use our LIDA seminar series recording, alas, this is [also broken](https://lida.leeds.ac.uk/seminar-series-23rd-june-2022/))
