### ISSUE TITLE
Data pack production - Ideas and example

### ISSUE THREAD

**Issue by hulsiejames** [udsleeds/openinfra#88]
Title says it all! 

I have been doing some work for #59 recently, with focus on the workflow to generate datapacks. 

I will upload an actual exmaple data pack for Leeds (current example) and close #59 for now - discussion relating to further development and the workflow can be discussed here!

Firstly, please see the html map I have [hosted on netlify](https://dazzling-dolphin-9a3873.netlify.app/) (.html is >120MB, thus too large for openinfraresults)

This is an interactive plot of the LAD Stroud (from [data-small/lads_joined_2021.geojson](https://github.com/udsleeds/openinfra/blob/main/data-small/lads_joined_2021.geojson)) that contains a number of "layers" you will need to select & de-select to observe. The layers are: 

| Layer Name| Description | 
| -------- | -------- |
|network | default OSM network returned from oe_get() |
|stroud_poly   | the polygon object defined in `lads_joined_2021.geojson` used to spatially subset the data|
|small_network| spatial subset of network --> `small_network = network[stroud_poly, ]`|
| stroud_road_class  | oi_recode_road function output with argument: `small_network` |
| stroud_maxspeed  | oi_clean_maxspeed_uk function output with argument: `small_network` |
| stroud_walking  | oi_active_walk function output with argument: `small_network` |
| stroud_cycling  | oi_active_cycle function output with argument: `small_network` |
| stroud_lighting  | oi_is_lit function output with argument: `small_network` |
| stroud_IM  | oi_inclusive_mobility function output with argument: `small_network`

**Comment by hulsiejames** [comment]
In creating the example above - I was testing a workflow idea. 

For each polygon within `lads_joined_2021` - request OSM data using each polygon as a query in osmextract. 

This works well, but is often getting much more data than required. 
For example, querying the Stroud polygon returned the area for Goloustershire, not just Stroud (this is expected...)

![](https://i.imgur.com/ZzNGpVE.png)

As hinted within the table above, I subset this total Gloustershrie network with the Stroud polygon again to get a more appropriate network: 
![](https://i.imgur.com/NBOmpat.png)

This has resulted in the Idea that, rather than requesting a network through osmextract for each LAD, and then re-subsetting the output network to be the same size of the LAD polygon, taking a lot of time and disc space, we instead just download England.osm.pbf and create each LAD network by subsetting the England network with each LAD polygon.

That is: 
```
England.osm.pbf = oe_get("England", layer="lines", extra_tags = required_tags)

for current_polygon in LADs:
   current_LAD = England.osm.pbf[current_polygon, ]
  # Apply openinfra functions to make & save a data_pack 
```

Rather than:
```
for current_polygon in LADs:
  current_LAD = oe_get(current_polygon, layer = "lines", extra_tags = required_tags)
  current_LAD = current_LAD[current_polygon, ]
  # Apply openinfra frunctions to make & save a data_pack
```

**Comment by hulsiejames** [comment]
Finally some thoughts on the spatial subsetting. 

As seen above, below, and described in [geocompr - spatial subsetting](https://geocompr.robinlovelace.net/spatial-operations.html#spatial-vec) the default subsetting operator used in the exmaples above is `st_intersects` *"a ‘catch all’ topological relation that will return features in the target that touch, cross or are within the source ‘subsetting’ object. "*

![](https://i.imgur.com/LuMb2vQ.png)

As described - this is the expected outcome - features have been included as they are crossing or touching the `stroud_poly` and have been included.

@Robinlovelace 
My main question would be is this a satisfactory output containing the end of ways that are no longer within `stroud_poly`? or should we try and find code that can include all of these ways, but essentially 'snip' them shorter if crossing a bounding polygon? 

I think I remember seeing something like this within the OSMnx package - I'll go and have a look and see if this is something that is simple to implement

**Comment by hulsiejames** [comment]
As seen in the above commit - you can run the script I used to create this map here: [test-code/test_data_pack_spatial_buffering.R](https://github.com/udsleeds/openinfra/commit/e52bc71e8397ea0e975c864090e1154b0e7a4c30#diff-a653229abc700b85fc69010fdf095cbaf9791b98909a8ce3b7d831e3812964b1)

**Comment by Robinlovelace** [comment]
> @Robinlovelace My main question would be is this a satisfactory output containing the end of ways that are no longer within `stroud_poly`? or should we try and find code that can include all of these ways, but essentially 'snip' them shorter if crossing a bounding polygon?

I think 'unsipped' is best in the first instance. Pretty busy today, will aim to look at this and provide more proper feedback by end of day tomorrow.

**Comment by hulsiejames** [comment]
Cheers.

No worries Robin, hope it's going okay! 

Will have a play with unsipped and see how it performs.

**Comment by hulsiejames** [comment]
Update: 

I have discovered `oe_get()` arugments `boundary` & `boundary_type`, that perform the filtering before even loading the file into R memory. (very useful as currently utilising 23GB RAM within rstudio alone - not feasable for most!)

This seems to be a much faster approach than one outlined in previous comments. 
Additionally, the `boundary_type="clipsrc"` has the desired network cropping effect! 

**clipsrc**
![](https://i.imgur.com/b9Fz0xp.png)

**spat**
![](https://i.imgur.com/09Ux1KA.png)

**Comment by hulsiejames** [comment]
Yeah, you definitely have! Though, I thought that was in reference to using a polygon as a search query for osmextract rather than the translate option. 

As you say it was quite interesting and a nice surprise to see the performance increase – I can say confidently that this has improved runtime by at least 100%.

Currently testing the functionality of subsetting each LAD from the England.osm.pbf and saving each LAD network as a geojson - this seems to be going well. 

Moving on I will apply each openinfra function to each LAD network and then re-upload these geojsons as the transport data packs!

**Comment by Robinlovelace** [comment]
This is really great progress. Given the rate of improvement I suggest a meeting is the best way forward. I will schedule a meeting with you James.

**Comment by hulsiejames** [comment]
Sounds good to me, Robin. I will come to meet you at ITS later.

**Comment by hulsiejames** [comment]
I will close this now as we currently have a production workflow for creating the data packs [create_data_packs.R](https://github.com/udsleeds/openinfra/blob/main/code/create_data_packs.R).

**Comment by Robinlovelace** [comment]
:tada:
