### ISSUE TITLE
sotm 2022 workshop

### ISSUE THREAD

**Issue by GretaTimaite** [udsleeds/openinfra#89]
SOTM is in a few weeks so I think it's more than a time to crack on. 
Here's the description: https://2022.stateofthemap.org/sessions/JEXYHK/

We have 60 minutes only, so we have to be spot on. What are your ideas on the structure of the workshop?
We promise to provide answers to the following questions, thus we have 10 minutes for each section:

    1. What gaps in transport evidence can OSM data fill in different countries?
    2. Which elements and tags are most important for transport planning (and how to get the data in reproducible data science environments)?
    3. How to filter based on different tags and their values?
    4. How to use OSM datasets to visualize transport systems in static and interactive maps?
    5. How to add value to OSM data and communicate results using R, Python and A/B Street, and osm2streets?

1. This looks a rather rhetoric one and get people thinking about the localised needs?
2. this one is also rather rhetoric. I guess this opens up space to tailor our material as per audience's needs and query/use the tags they think as important (they are OSM experts after all).
---> I think it would be good to incorporate "live coding" approach? Or at least have a template and show how it can be modified to suit their needs
3. Basic filtering either using R or SQL? I guess both approaches can be used. SQL could be an extra exercise for those the advanced programmers
4. base R, tmap, mapview options?
5. recategorisation? file rendering (ie communication)?

In general, following the questions looks like a sensible structure to the workshop as it incorporates both discussion and coding. What are your thoughts @hulsiejames and @Robinlovelace?

Also, we note that it is suitable for beginners, so I reckon that it may be useful to spend 5-10 minutes to introduce R syntax (I guess we will go for tidy approach) and RStudio IDE.

Another point, we need to send out R + RStudio installation instructions, yet my experience is that there WILL be people who do not have it installed for one reason or another. For this we might want to explore web-based options, such as use [`learnr` package](https://rstudio.github.io/learnr/) as to avoid wasting time on installing r during the session. Installation can be especially tricky when it has to be done remotely.

Finally, @Robinlovelace you're not on workshop author list, are you intending to take part in it? I did think you will be leading it as you have the most experience while James and I can prep the material + be assistants.

**Comment by hulsiejames** [comment]
Really like the look of the structure here Greta, specifially the questions! 

Specificaly the rhetorical nautre of 1 & 2. I think these should be the last things we cover (especially 1.) as if we saet up the context and examples some of these questions will be answered by participaants whilst engaging with 3-5. 

Will come back and add some more thought to this tomorrow morning!

**Comment by GretaTimaite** [comment]
I, honestly, think questions 1 and 2 should be asked first to get them thinking, but also keep these questions open, so participants can return to them when thinking about, for instance, question 5. I'll let Robin decide on this as he heavily contributed to the submission.

**Comment by hulsiejames** [comment]
Looks good - I think I might agree with you there too actually.  



I know we say beginners, but if you have turned up to SOTM2022 you clearly won't be a 'beginner', at least I expect participants will know of Ways, Nodes & Relations and that features are described by tags, meaning participants should be able to think about these questions as you say.    

3 - I think we should focus on R, but also cover the ability to really define your queries through SQL for those interested. 

4 - We can/have made some nice-looking maps with tmap before to visualise these networks.  

5 - IM and Openinfra functions? Could mention the project site?

**Comment by GretaTimaite** [comment]
@hulsiejames, when I refer to a "beginner level", I mean programming in general and knowledge of R specifically. Not a beginner in OSM.

> 3 - I think we should focus on R, but also cover the ability to really define your queries through SQL for those interested.

Yes, focus should be on R. However, in one of the seminars on teaching DS, I've heard that it is a good idea to include some more advanced examples for the more advanced ones (if one expects any). 

5 - IM and Openinfra functions? Could mention the project site?

I think this is a fair thing to include. Plus, it would create an opportunity to receive feedback.

**Comment by GretaTimaite** [comment]
Where should we store the material? As an OI vignette or should we create a separate repo for the workshop?

**Comment by hulsiejames** [comment]
> Where should we store the material? As an OI vignette or should we create a separate repo for the workshop?

An OI vignette could be good - combining practical things with a written guide but I like the idea of a repo too that people can clone and then get all relevant files. Though, this assumes that participants will have a github account and are comfotable cloning a repo, a google drive could be another idea?

**Comment by GretaTimaite** [comment]
I guess the easiest way is to ask participants to have R + Rstudio installed + quorto? and they can copy/paste code and modify it as they want. I guess I'll have a quick look into [RStudio Cloud](https://rstudio.cloud/) option, so they can code from the browser as, again, someone is bound to have installation issues

**Comment by GretaTimaite** [comment]
Also, I liked the idea of creating an issue for the installation issues and provide a quick example code that, given all the packages are installed, would plot a small map: https://github.com/ITSLeeds/pct/issues/110

**Comment by hulsiejames** [comment]
> I guess the easiest way is to ask participants to have R + Rstudio installed + quorto? and they can copy/paste code and modify it as they want. I guess I'll have a quick look into [RStudio Cloud](https://rstudio.cloud/) option, so they can code from the browser as, again, someone is bound to have installation issues

Yes as a bare minimum we can provide a link to the R install guide you sent me the other day on setting up R & Rstudio.

Agree a quarto or Rmd would be benficial to hold code than can then be run locally/another option.

I have had a couple issues using Quarto before and feel .Rmd would be more robust and less likely to give issues to participants, unless there is a specific reason you wish to use Quarto.

**Comment by hulsiejames** [comment]
> Also, I liked the idea of creating an issue for the installation issues and provide a quick example code that, given all the packages are installed, would plot a small map: [ITSLeeds/pct#110](https://github.com/ITSLeeds/pct/issues/110)

As in provide some code at the end of the isntallation guide, get particiapants to run this code to check that installation has coccured successfully?

**Comment by hulsiejames** [comment]
I will have a look at creating a installation guide, something similar to [this](https://datacarpentry.org/socialsci-workshop/setup-r-workshop.html). 

Steps: 
- Install base-r
- Install Rstudio
- Install required packages (osmextract, openinfra, sf, tmap, dplyr, etc...)
- Run example code (downloads some data & creates a plot as suggested in Greta's last comment)

**Comment by GretaTimaite** [comment]
Just was thinking that doing live coding might be the best approach. IE we have vignette to guide us but we write code with participants. It will be much more natural and give them enough time to follow but also might present opportunities to demonstrate how we deal with bugs/errors

**Comment by Robinlovelace** [comment]
I'm taking a quick look at the workshop materials now...

**Comment by GretaTimaite** [comment]
> I'm taking a quick look at the workshop materials now...

Thanks, just pushed some changes. Feel free to add more examples, especially in relation to A/B Street and/or osm2streets (ie point 5: How to add value to OSM data and communicate results using R, Python and A/B Street, and osm2streets?)

**Comment by GretaTimaite** [comment]
> I'm taking a quick look at the workshop materials now...

Thanks, just pushed some changes. Feel free to add more examples, especially in relation to A/B Street and/or osm2streets (ie point 5: How to add value to OSM data and communicate results using R, Python and A/B Street, and osm2streets?)

**Comment by GretaTimaite** [comment]
> I'm taking a quick look at the workshop materials now...

Thanks, just pushed some changes. Feel free to add more examples, especially in relation to A/B Street and/or osm2streets (ie point 5: How to add value to OSM data and communicate results using R, Python and A/B Street, and osm2streets?)

**Comment by GretaTimaite** [comment]
> I'm taking a quick look at the workshop materials now...

Thanks, just pushed some changes. Feel free to add more examples, especially in relation to A/B Street and/or osm2streets (ie point 5: How to add value to OSM data and communicate results using R, Python and A/B Street, and osm2streets?)

**Comment by GretaTimaite** [comment]
Quick update: included A/B Street in the [workshop vignette](https://udsleeds.github.io/openinfra/articles/SOTM_workshop.html#openinfra), I guess some concluding remarks/further steps and it's good to go? I think we can address the needs of the participants on the spot, if needed.

**Comment by Robinlovelace** [comment]
Great stuff. I've just put in a PR #100
