### ISSUE TITLE
sotm 2022 presentation

### ISSUE THREAD

**Issue by GretaTimaite** [udsleeds/openinfra#90]
Abstract is here: https://2022.stateofthemap.org/sessions/CEMMTQ/

I wrote the abstract quite abstract (pardon the pun), so it can be tailored to the direction project takes as it was submitted with an idea of @hulsiejames presenting it. Are you still fine with it?

I've not been following the project closely in the last 2-3 weeks, so I'm not exactly sure where it is and what direction you would like to take @hulsiejames and @Robinlovelace. I'm open and not pretentious here as long as it incorporates some of the stuff I've written about in the abstract (after all that's the material that got accepted). Also I recall one of the reviewers asking for a more concrete example of the OSM application in sustainable travel planning, thus, I think this should be incorporated as well. That concrete application could be, I reckon, a more extensive example of active travel network that could also lead to further discussion of OSM potential (open access, "streaming", citizen-centric) and limitations (missing data). Dunno it's my thinking. 

We are given 20 minutes for the presentation + approx 10 minutes for the Q&A

**Comment by GretaTimaite** [comment]
@hulsiejames  and I will be presenting together.

**Comment by GretaTimaite** [comment]
I'm thinking of  the following structure:

1. start by noting global health and environmental issue
2. mention that a shift to sustainable transport, especially active travel, is seen as one of the ways to remedy the situation. However, the infrastructure is still missing, so uptake is not great
3. policy makers in the UK want localised data-driven evidence to inform transport policies
4. **To what extent is OSM useful to support increasing demand for local evidence?**
     -> this is a leading question to our project
5. Discuss how OSM is currently used in transport research (basically the first 2 paras of the abstract)
6. Introduce OI/what we do
7. Most likely we could briefly discuss some bits from GISRUK in the context of missing data
8. Bring the idea that missing data != not useful data
9. Applications of OSM:
      a. IM function 
      b. LTN1/20

Support everything with some pretty photos, graphs, and maps. 

I think this would definitely take 15-20 minutes!

**Comment by hulsiejames** [comment]
I really like the look of this, I think it would have a good flow to present!  

  

> 4. **To what extent is OSM useful to support increasing demand for local evidence? ** 
>    -> this is a leading question to our project 



Could we discuss transport infrastructure data packs here - collating (hopefully local) crowd sourced data to act as local evidence for policy makers and urban planners? Or at least if not here, maybe within 6. / 7. referring to 4.  

 
i.e. a potential solution is the collection and analysis of locally sourced data, obtained after a local campaign encouraging the local community to add to OSM

**Comment by hulsiejames** [comment]
> 8. Bring the idea that missing data != not useful data

After some issues with LTN1/20, specifically the level of segregation of cycling infrastructure within OSM, I am a big supporter of this. 

The data is not unusable or an inappropriate format - it just hasn't been created/input yet to be able to accurately detect levels of segregation

**Comment by GretaTimaite** [comment]
I'd expect this question to what you demonstrate @hulsiejames : what would be your suggestion to solve this problem? Add more data? Join with other datasets as it might be too much to expect mappers to provide all of this info because how time-demanding it would be?

**Comment by Robinlovelace** [comment]
Do you have draft slides for this @hulsiejames and @GretaTimaite ? Happy to draft some in Xaringan if not... I think a quick demo of osm2streets would be great to show how we can extend the concept by using a great new 'way geometry expansion' tool from @dabreegster.

**Comment by dabreegster** [comment]
Catching up on the question here about figuring out if something is LTN120 compliant by looking at OSM data... That's also something I'm hoping to make progress towards with osm2streets. Two ideas for further discussion:

1) https://wiki.openstreetmap.org/wiki/Proposed_features/separation is a tag you can put on the cycleway to mark what kind of separation exists between it and the road. This is a pretty thorough schema proposal and is already being used in lots of places.

2) I'm working on transformations in osm2streets right now to "merge" parallel cycleways with the main road way. See https://github.com/a-b-street/osm2streets/pull/61. This example in Leeds doesn't work right now, but I can add a test case for it and start working on it.

**Comment by hulsiejames** [comment]
@Robinlovelace We have some draft slides on powerpoint - trying to generate a shared link but wifi on the train is quite slow!

**Comment by hulsiejames** [comment]
@Robinlovelace 

https://leeds365-my.sharepoint.com/:p:/g/personal/medgti_leeds_ac_uk/EawrjwB4MyRCns-ul11wGm4BUzGlf2qQfNmlbxc5fP4sBw?e=Rs3tG7 

Apologies for the delay - poor wifi!

**Comment by hulsiejames** [comment]
>https://wiki.openstreetmap.org/wiki/Proposed_features/separation is a tag you can put on the cycleway to mark what kind of separation exists between it and the road. This is a pretty thorough schema proposal and is already being used in lots of places.

This is something I welcome very much! I have had some issues when trying to assess the level of segregation from tags alone and look forward to exploring this some more. 

It is a shame I had not seen this earlier as I'm certain it will be useful.

**Comment by Robinlovelace** [comment]
Thanks for sharing the slides James, will take a look on the train.
