### ISSUE TITLE
oi_name 

### ISSUE THREAD

**Issue by hulsiejames** [udsleeds/openinfra#95]
oi_name will be `ref` & `name` or whichever is available 

for example 

oi_name = paste0(ref, name)

**Comment by hulsiejames** [comment]
![](https://i.imgur.com/NkVEIZD.png)

Looks good. 

Once checks are done, I'll get it up.

**Comment by Robinlovelace** [comment]
See #97 I'm a fan of the pipe operator usually, but not in road names!

**Comment by hulsiejames** [comment]
Cheers, bit of an oversight using the pipe there! 

It's been implemented with [02a4cda](https://github.com/udsleeds/openinfra/commit/02a4cda7edad70d3521e830c974d0a219ceac456).

**Comment by Robinlovelace** [comment]
Great. Feel free to close now or after data packs with this have been released.
